-- ChickenFutsal: un gruppo privato, stagioni e turni indipendenti per premio.
-- Eseguire una volta nel SQL Editor Supabase. Nessuna tabella è leggibile dal client.
create schema if not exists club_private;
revoke all on schema club_private from public, anon, authenticated;
create table club_private.players (
 id bigint generated by default as identity primary key,
 name text not null check(length(name) between 1 and 60),
 role text not null default 'Regista',
 occasional boolean not null default false,
 active boolean not null default true,
 ratings jsonb not null default '[60,60,60,60,60,60]'::jsonb
);
create table club_private.members (
 player_id bigint primary key references club_private.players(id),
 email text unique not null check(email=lower(email)),
 is_admin boolean not null default false,
 see_all boolean not null default false
);
create table club_private.matches (
 id bigint generated always as identity primary key,
 season integer not null,
 match_date date not null,
 match_time time not null,
 field text not null check(length(field) between 1 and 100),
 team_a jsonb not null, team_b jsonb not null,
 cancelled_at timestamptz, cancellation_reason text check(length(cancellation_reason)<=200),
 result jsonb, updated_at timestamptz not null default now()
);
create table club_private.rounds (
 id bigint generated always as identity primary key,
 season integer not null,
 award text not null check(award in ('pollone','bidone')),
 turn integer not null check(turn between 1 and 4),
 candidates jsonb not null,
 status text not null default 'open' check(status in ('open','closed','final')),
 unique(season,award,turn)
);
create table if not exists club_private.seasons (
 id integer primary key, name text not null check(length(name) between 1 and 60),
 started_on date not null, closed_at timestamptz
);
create unique index if not exists one_active_season on club_private.seasons ((true)) where closed_at is null;
insert into club_private.seasons(id,name,started_on,closed_at)
select y,case when y=2026 then '2025/2026' else y::text end,make_date(y,1,1),case when y=max(y) over() then null else now() end
from (select season y from club_private.matches union select season from club_private.rounds union select 2026) t
on conflict(id) do nothing;
alter table club_private.seasons enable row level security;

-- Segretezza verso gli admin dell'app; gli operatori del database possono leggere queste tabelle.
create table club_private.ballots (
 round_id bigint not null references club_private.rounds(id),
 voter_id bigint not null references club_private.players(id),
 candidate_id bigint not null references club_private.players(id),
 primary key(round_id,voter_id)
);
create table club_private.notifications (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 match_id bigint not null references club_private.matches(id),
 text text not null, seen boolean not null default false,
 created_at timestamptz not null default now()
);
create table club_private.push_subscriptions (
 player_id bigint not null references club_private.players(id),
 endpoint text primary key, subscription jsonb not null,
 created_at timestamptz not null default now()
);
create table club_private.push_queue (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 notification_id bigint not null references club_private.notifications(id),
 status text not null default 'pending' check(status in ('pending','processing','sent','failed')),
 attempts integer not null default 0,
 claim_token uuid, claimed_at timestamptz, created_at timestamptz not null default now()
);
create table club_private.audit (
 id bigint generated always as identity primary key, actor bigint not null,
 action text not null, created_at timestamptz not null default now()
);
-- Defense in depth. No client policies: access is through checked RPC functions only.
alter table club_private.players enable row level security;
alter table club_private.members enable row level security;
alter table club_private.matches enable row level security;
alter table club_private.rounds enable row level security;
alter table club_private.ballots enable row level security;
alter table club_private.notifications enable row level security;
alter table club_private.push_subscriptions enable row level security;
alter table club_private.push_queue enable row level security;
alter table club_private.audit enable row level security;

create function club_private.actor() returns bigint language plpgsql stable security definer set search_path='' as $$
declare v_id bigint;
begin
 if auth.uid() is null then raise exception 'Accedi al gruppo'; end if;
 select m.player_id into v_id from club_private.members m
 join auth.users u on lower(u.email)=m.email
 join club_private.players p on p.id=m.player_id and p.active
 where u.id=auth.uid() and u.email_confirmed_at is not null;
 if v_id is null then raise exception 'Account non invitato o email non confermata'; end if;
 return v_id;
end $$;
revoke all on function club_private.actor() from public;

create table if not exists club_private.season_awards (
 season integer primary key references club_private.seasons(id),
 awards jsonb not null, captured_at timestamptz not null default now()
);
alter table club_private.season_awards enable row level security;
revoke all on club_private.season_awards from public,anon,authenticated;
-- This function is private: closure calls it inside the same transaction.
create or replace function club_private.capture_awards(p_season integer) returns void
language plpgsql security definer set search_path='' as $$
declare v_awards jsonb; v_award text; v_winners jsonb;
begin
 if exists(select 1 from club_private.season_awards where season=p_season) then return; end if;
  with totals as (
   select p.id,p.name,coalesce(sum((r.value->>'goals')::int),0) goals,
    coalesce(sum((r.value->>'own')::int),0) own,
    count(*) filter(where (r.value->>'present')::boolean) apps
   from club_private.players p left join club_private.matches m on m.season=p_season and m.cancelled_at is null and m.result ? p.id::text
   left join lateral jsonb_each(m.result) r on r.key=p.id::text group by p.id,p.name
  ), scores as (
   select t.id,t.name,v.metric,v.total from totals t cross join lateral (values ('goals',t.goals),('own',t.own),('apps',t.apps)) v(metric,total)
  ), ranked as (
   select *,max(total) over(partition by metric) maximum from scores
  ), winners as (
   select metric,jsonb_agg(jsonb_build_object('id',id,'name',name) order by id) identities from ranked where total=maximum and maximum>0 group by metric
  ) select coalesce(jsonb_object_agg(metric,identities),'{}'::jsonb) into v_awards from winners;
 v_awards:=jsonb_build_object('goals','[]'::jsonb,'own','[]'::jsonb,'apps','[]'::jsonb)||v_awards;
 foreach v_award in array array['pollone','bidone'] loop
  with latest as (
   select id,status from club_private.rounds where season=p_season and award=v_award order by turn desc limit 1
  ), counts as (
   select p.id,p.name,count(*) votes from latest r join club_private.ballots b on b.round_id=r.id
   join club_private.players p on p.id=b.candidate_id where r.status='final' group by p.id,p.name
  ) select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by id),'[]'::jsonb)
   into v_winners from counts where votes=(select max(votes) from counts);
  v_awards:=v_awards||jsonb_build_object(v_award,v_winners);
 end loop;
 insert into club_private.season_awards(season,awards) values(p_season,v_awards) on conflict(season) do nothing;
end $$;
revoke all on function club_private.capture_awards(integer) from public,anon,authenticated;

create table if not exists club_private.reminder_settings (
 singleton boolean primary key default true check(singleton),
 participant_enabled boolean not null default true,
 first_enabled boolean not null default true,
 first_hours numeric not null default 8 check(first_hours between 0.25 and 168),
 second_enabled boolean not null default true,
 second_hours numeric not null default 1 check(second_hours between 0.25 and 168),
 result_enabled boolean not null default true,
 match_duration_minutes integer not null default 60 check(match_duration_minutes between 15 and 240),
 result_delay_hours numeric not null default 1 check(result_delay_hours between 0 and 168),
 result_repeat_enabled boolean not null default false,
 result_repeat_hours numeric not null default 24 check(result_repeat_hours between 1 and 168),
 result_max_reminders integer not null default 3 check(result_max_reminders between 1 and 20),
 check(not(participant_enabled and first_enabled and second_enabled) or first_hours>second_hours)
);
insert into club_private.reminder_settings(singleton) values(true) on conflict(singleton) do nothing;
alter table club_private.reminder_settings enable row level security;
revoke all on club_private.reminder_settings from public,anon,authenticated;
alter table club_private.notifications add column if not exists reminder_key text;
create unique index if not exists notification_reminder_once on club_private.notifications(match_id,player_id,reminder_key) where reminder_key is not null;

-- Called by the existing service-only push queue RPC every time the sender runs.
create or replace function club_private.enqueue_reminders(p_now timestamptz default now()) returns integer
language plpgsql security definer set search_path='' as $$
declare
 cfg club_private.reminder_settings%rowtype; m club_private.matches%rowtype;
 kickoff timestamptz; due timestamptz; result_due timestamptz; offset_hours numeric;
 offsets numeric[]; pid bigint; note bigint; key text; reminder_number integer; added integer:=0;
begin
 perform pg_advisory_xact_lock(712026);
 select * into cfg from club_private.reminder_settings where singleton;
 if not found then return 0; end if;
 -- Suppress stale queued reminders before sending, including cancelled games, completed
 -- scores, removed participants/admins, disabled reminders and past kickoffs.
 update club_private.push_queue q set status='sent',claim_token=null
 from club_private.notifications n join club_private.matches mm on mm.id=n.match_id
 where q.notification_id=n.id and n.reminder_key is not null and q.status<>'sent' and (
  mm.cancelled_at is not null or mm.result is not null or
  not exists(select 1 from club_private.seasons where id=mm.season and closed_at is null) or
  (n.reminder_key like 'participant:%' and (
   not cfg.participant_enabled or
   not(mm.team_a @> jsonb_build_array(n.player_id) or mm.team_b @> jsonb_build_array(n.player_id)) or
   p_now>=(mm.match_date+mm.match_time) at time zone 'Europe/Rome' or
   not (
    (cfg.first_enabled and n.reminder_key='participant:'||extract(epoch from ((mm.match_date+mm.match_time) at time zone 'Europe/Rome')-cfg.first_hours*interval '1 hour')::bigint::text) or
    (cfg.second_enabled and n.reminder_key='participant:'||extract(epoch from ((mm.match_date+mm.match_time) at time zone 'Europe/Rome')-cfg.second_hours*interval '1 hour')::bigint::text)
   ) or
   (cfg.second_enabled and p_now>=((mm.match_date+mm.match_time) at time zone 'Europe/Rome')-cfg.second_hours*interval '1 hour' and
    n.reminder_key<>'participant:'||extract(epoch from ((mm.match_date+mm.match_time) at time zone 'Europe/Rome')-cfg.second_hours*interval '1 hour')::bigint::text)
  )) or
  (n.reminder_key like 'result:%' and (not cfg.result_enabled or not exists(select 1 from club_private.members where player_id=n.player_id and is_admin) or
   not exists(select 1 from generate_series(0,case when cfg.result_repeat_enabled then cfg.result_max_reminders-1 else 0 end) i where
    n.reminder_key='result:'||extract(epoch from ((mm.match_date+mm.match_time) at time zone 'Europe/Rome')+cfg.match_duration_minutes*interval '1 minute'+cfg.result_delay_hours*interval '1 hour'+i*cfg.result_repeat_hours*interval '1 hour')::bigint::text)))
 );
 for m in select mm.* from club_private.matches mm join club_private.seasons s on s.id=mm.season
  where s.closed_at is null and mm.cancelled_at is null and mm.result is null loop
  kickoff:=(m.match_date+m.match_time) at time zone 'Europe/Rome';
  if cfg.participant_enabled and p_now<kickoff then
   offsets:=array[]::numeric[];
   if cfg.first_enabled then offsets:=array_append(offsets,cfg.first_hours); end if;
   if cfg.second_enabled then offsets:=array_append(offsets,cfg.second_hours); end if;
   -- Recover only the latest due reminder, never send both at once after an outage.
   select min(h) into offset_hours from unnest(offsets) h where p_now>=kickoff-h*interval '1 hour';
   if offset_hours is not null then
    due:=kickoff-offset_hours*interval '1 hour';key:='participant:'||extract(epoch from due)::bigint::text;
    -- A match created/rescheduled after this deadline already sent its own update notice.
    if m.updated_at<=due then
     for pid in select members.player_id from club_private.members members join club_private.players p on p.id=members.player_id and p.active where m.team_a @> jsonb_build_array(members.player_id) or m.team_b @> jsonb_build_array(members.player_id) loop
      note:=null;
      insert into club_private.notifications(player_id,match_id,text,reminder_key)
       values(pid,m.id,'Promemoria partita: '||m.match_date::text||' alle '||to_char(m.match_time,'HH24:MI')||' · '||m.field,key)
       on conflict(match_id,player_id,reminder_key) where reminder_key is not null do nothing returning id into note;
      if note is not null then insert into club_private.push_queue(player_id,notification_id) values(pid,note);added:=added+1;end if;
     end loop;
    end if;
   end if;
  end if;
  if cfg.result_enabled then
   result_due:=kickoff+cfg.match_duration_minutes*interval '1 minute'+cfg.result_delay_hours*interval '1 hour';
   if p_now>=result_due then
    reminder_number:=0;
    if cfg.result_repeat_enabled then reminder_number:=least(cfg.result_max_reminders-1,floor(extract(epoch from (p_now-result_due))/(cfg.result_repeat_hours*3600))::integer); end if;
    due:=result_due+reminder_number*cfg.result_repeat_hours*interval '1 hour';
    key:='result:'||extract(epoch from due)::bigint::text;
    for pid in select members.player_id from club_private.members members join club_private.players p on p.id=members.player_id and p.active where members.is_admin loop
     note:=null;
     insert into club_private.notifications(player_id,match_id,text,reminder_key)
      values(pid,m.id,'Risultato da registrare: partita del '||m.match_date::text||' alle '||to_char(m.match_time,'HH24:MI')||' · '||m.field,key)
      on conflict(match_id,player_id,reminder_key) where reminder_key is not null do nothing returning id into note;
     if note is not null then insert into club_private.push_queue(player_id,notification_id) values(pid,note);added:=added+1;end if;
    end loop;
   end if;
  end if;
 end loop;
 return added;
end $$;
revoke all on function club_private.enqueue_reminders(timestamptz) from public,anon,authenticated,service_role;

alter table club_private.audit add column if not exists actor_name text;
alter table club_private.audit add column if not exists subject text;
alter table club_private.audit add column if not exists details jsonb not null default '{}'::jsonb;
create table if not exists club_private.deleted_players (
 player_id bigint primary key, profile jsonb not null,
 deleted_at timestamptz not null default now(), deleted_by_name text not null
);
alter table club_private.deleted_players enable row level security;
revoke all on club_private.deleted_players from public,anon,authenticated;
create or replace function public.club_admin_history() returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint;
begin
 v_actor:=club_private.actor();
 if not exists(select 1 from club_private.members where player_id=v_actor and is_admin) then raise exception 'Operazione riservata agli admin'; end if;
 return jsonb_build_object(
 'changes',(select coalesce(jsonb_agg(to_jsonb(a) order by a.id desc),'[]'::jsonb) from (select a.id,a.created_at,coalesce(a.actor_name,p.name,'Admin #'||a.actor::text) actor_name,a.action,a.subject,a.details from club_private.audit a left join club_private.players p on p.id=a.actor order by a.id desc limit 10) a),
 'deletedPlayers',(select coalesce(jsonb_agg(jsonb_build_object('id',player_id,'name',profile->>'name','role',profile->>'role','deletedAt',deleted_at,'deletedBy',deleted_by_name) order by deleted_at desc),'[]'::jsonb) from club_private.deleted_players));
end $$;
revoke all on function public.club_admin_history() from public,anon;
grant execute on function public.club_admin_history() to authenticated;

-- Avatar raster compatti, privati e accessibili solo ai membri del gruppo.
alter table club_private.players add column if not exists image_data text;
alter table club_private.players add column if not exists image_version text generated always as (case when image_data is not null then md5(image_data) else null end) stored;
alter table club_private.players add column if not exists default_image integer not null default 1 check(default_image in (1,2));
create table if not exists club_private.performance_settings (
 singleton boolean primary key default true check(singleton),
 step numeric not null default 0.5 constraint performance_settings_allowed_step check(step in (0,0.5,1))
);
insert into club_private.performance_settings(singleton) values(true) on conflict do nothing;
create table if not exists club_private.rating_events (
 id bigint generated by default as identity primary key,
 player_id bigint not null,
 match_id bigint references club_private.matches(id) on delete cascade,
 base_values jsonb,judgment text,step numeric,delta numeric,
 unique(player_id,match_id),
 check((match_id is null and base_values is not null) or
 (match_id is not null and base_values is null and judgment in ('below','same','above') and step between 0 and 5 and delta between -5 and 5))
);
create index if not exists rating_events_player_order on club_private.rating_events(player_id,id);
alter table club_private.performance_settings enable row level security;
alter table club_private.rating_events enable row level security;
revoke all on club_private.performance_settings,club_private.rating_events from public,anon,authenticated;
-- Private events are retained while a player is archived, to allow accurate recovery.
create or replace function club_private.replay_ratings(p_player bigint) returns jsonb
language plpgsql set search_path='' as $$
declare v_values jsonb;v_event record;
begin
 for v_event in select * from club_private.rating_events where player_id=p_player order by id loop
  if v_event.base_values is not null then v_values:=v_event.base_values;
  elsif v_values is not null then
   select jsonb_agg(greatest(1,least(99,round(value::text::numeric+v_event.delta,2))) order by ord)
   into v_values from jsonb_array_elements(v_values) with ordinality as a(value,ord);
  end if;
 end loop;
 return v_values;
end $$;
revoke all on function club_private.replay_ratings(bigint) from public,anon,authenticated;
create or replace function club_private.sync_match_ratings(p_match bigint,p_actor bigint) returns void
language plpgsql set search_path='' as $$
declare v_match club_private.matches%rowtype;v_player bigint;v_before jsonb;v_after jsonb;v_name text;v_actor_name text;
 v_entry jsonb;v_judgment text;v_previous club_private.rating_events%rowtype;v_step numeric;v_delta numeric;v_changed boolean;
begin
 select * into v_match from club_private.matches where id=p_match;
 select step into v_step from club_private.performance_settings where singleton;
 select name into v_actor_name from club_private.players where id=p_actor;
 for v_player in select distinct pid from (
  select player_id pid from club_private.rating_events where match_id=p_match
  union select key::bigint from jsonb_each(coalesce(v_match.result,'{}'::jsonb))) affected order by pid loop
  select ratings,name into v_before,v_name from club_private.players where id=v_player for update;
  v_entry:=v_match.result->v_player::text;
  v_judgment:=case when v_match.cancelled_at is null and coalesce((v_entry->>'present')::boolean,false)
    and (v_match.team_a||v_match.team_b) @> jsonb_build_array(v_player)
    then nullif(v_entry->>'performance','') else null end;
  select * into v_previous from club_private.rating_events where player_id=v_player and match_id=p_match;
  v_changed:=v_previous.judgment is distinct from v_judgment;
  if v_judgment is null then delete from club_private.rating_events where player_id=v_player and match_id=p_match;
  elsif v_before is not null then
   if not exists(select 1 from club_private.rating_events where player_id=v_player and base_values is not null) then
    insert into club_private.rating_events(player_id,base_values) values(v_player,v_before);
   end if;
   -- Keep the saved magnitude when correcting only goals or other fields.
   if v_previous.judgment=v_judgment then v_delta:=v_previous.delta;
   else v_delta:=case v_judgment when 'above' then v_step when 'below' then -v_step else 0 end;end if;
   insert into club_private.rating_events(player_id,match_id,judgment,step,delta) values(v_player,p_match,v_judgment,
    case when v_previous.judgment=v_judgment then v_previous.step else v_step end,v_delta)
    on conflict(player_id,match_id) do update set judgment=excluded.judgment,step=excluded.step,delta=excluded.delta;
  end if;
  if v_before is not null and exists(select 1 from club_private.rating_events where player_id=v_player) then
   v_after:=club_private.replay_ratings(v_player);
   if v_after is not null then update club_private.players set ratings=v_after where id=v_player;end if;
   if v_after is distinct from v_before or v_changed then
    insert into club_private.audit(actor,actor_name,action,subject,details) values(p_actor,v_actor_name,'performance_ratings',v_name,
     jsonb_build_object('matchId',p_match,'judgment',v_judgment,'before',jsonb_build_object('ratings',v_before),
      'after',jsonb_build_object('ratings',coalesce(v_after,v_before))));
   end if;
  end if;
 end loop;
end $$;
revoke all on function club_private.sync_match_ratings(bigint,bigint) from public,anon,authenticated;
create or replace function public.club_snapshot(p_season integer default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint; v_admin boolean; v_all boolean; v_players jsonb; v_matches jsonb; v_rounds jsonb; v_awards jsonb;
begin
 v_actor:=club_private.actor();
 if p_season is null then select id into p_season from club_private.seasons where closed_at is null; end if;
 if not exists(select 1 from club_private.seasons where id=p_season) then raise exception 'Stagione non valida'; end if;
 select is_admin,see_all into v_admin,v_all from club_private.members where player_id=v_actor;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'role',p.role,
 'defaultImage',p.default_image,'imageVersion',p.image_version,'occasional',p.occasional,'active',p.active,'hasPresence',coalesce(s.apps,0)>0,'admin',coalesce(m.is_admin,false),'seeAll',case when v_admin or p.id=v_actor then coalesce(m.see_all,false) else false end)
 || case when v_admin or v_all or p.id=v_actor then jsonb_build_object('ratings',p.ratings,
 'goals',coalesce(s.goals,0),'own',coalesce(s.own,0),'apps',coalesce(s.apps,0),
 'wins',coalesce(s.wins,0),'draws',coalesce(s.draws,0),'losses',coalesce(s.losses,0),
 'winRate',case when s.apps>0 then round(100.0*s.wins/s.apps,2) else 0 end,
 'goalAverage',case when s.apps>0 then round(s.goals::numeric/s.apps,2) else 0 end) else '{}'::jsonb end
 || case when v_admin then jsonb_build_object('email',m.email) else '{}'::jsonb end order by p.id),'[]'::jsonb)
 into v_players from club_private.players p left join club_private.members m on m.player_id=p.id
 left join lateral (
 select sum((r.value->>'goals')::integer) goals,sum((r.value->>'own')::integer) own,
 count(*) filter(where (r.value->>'present')::boolean) apps,
 count(*) filter(where (r.value->>'present')::boolean and
  case when mm.team_a @> jsonb_build_array(p.id) then score.a>score.b else score.b>score.a end) wins,
 count(*) filter(where (r.value->>'present')::boolean and score.a=score.b) draws,
 count(*) filter(where (r.value->>'present')::boolean and
  case when mm.team_a @> jsonb_build_array(p.id) then score.a<score.b else score.b<score.a end) losses
 from club_private.matches mm cross join lateral jsonb_each(mm.result) r
 cross join lateral (
  select coalesce(sum(case when mm.team_a @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) a,
   coalesce(sum(case when mm.team_b @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) b
  from jsonb_each(mm.result) e
 ) score
 where mm.season=p_season and mm.cancelled_at is null and r.key=p.id::text
 ) s on true;
 select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'date',m.match_date,'time',to_char(m.match_time,'HH24:MI'),
 'field',m.field,'cancelled',m.cancelled_at is not null,'cancellationReason',m.cancellation_reason,'a',m.team_a,'b',m.team_b,'done',m.result is not null,
 'score',case when m.result is null then null else jsonb_build_array(
 (select coalesce(sum(case when m.team_a @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r),
 (select coalesce(sum(case when m.team_b @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r)) end,
 'result',case when m.result is null then null when v_admin or v_all then m.result else (select coalesce(jsonb_object_agg(r.key,r.value),'{}'::jsonb) from jsonb_each(m.result) r where r.key=v_actor::text) end) order by m.match_date,m.match_time),'[]'::jsonb)
 into v_matches from club_private.matches m where m.season=p_season;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'award',r.award,'turn',r.turn,'status',r.status,'candidates',r.candidates,
 'voted',exists(select 1 from club_private.ballots b where b.round_id=r.id and b.voter_id=v_actor),
 'count',(select count(*) from club_private.ballots b where b.round_id=r.id),
 'results',case when r.status<>'open' then coalesce((select jsonb_agg(jsonb_build_object('id',a.candidate_id,'count',a.n) order by a.n desc,a.candidate_id)
 from (select b.candidate_id,count(*) n from club_private.ballots b where b.round_id=r.id group by b.candidate_id) a),'[]'::jsonb) else '[]'::jsonb end)
 order by r.award,r.turn),'[]'::jsonb) into v_rounds from club_private.rounds r where r.season=p_season;
 v_awards:=coalesce((select awards from club_private.season_awards where season=p_season),'{}'::jsonb);
 return jsonb_build_object('user',v_actor,'season',p_season,'players',v_players,'matches',v_matches,'rounds',v_rounds,
 'performanceSettings',(select jsonb_build_object('step',step) from club_private.performance_settings where singleton),
 'reminderSettings',case when v_admin then (select to_jsonb(c)-'singleton' from club_private.reminder_settings c where singleton) else null end,
 'closedAwards',v_awards,
 'hallOfFame',(select coalesce(jsonb_agg(jsonb_build_object('season',s.id,'name',s.name,'closedAt',s.closed_at,'awards',a.awards) order by s.id desc),'[]'::jsonb) from club_private.seasons s join club_private.season_awards a on a.season=s.id where s.closed_at is not null),
 'activeSeason',(select id from club_private.seasons where closed_at is null),
 'seasonInfo',(select to_jsonb(s) from club_private.seasons s where id=p_season),
 'seasons',(select jsonb_agg(id order by id desc) from club_private.seasons),
 'seasonOptions',(select jsonb_agg(to_jsonb(s) order by id desc) from club_private.seasons s),
 'notifications',(select coalesce(jsonb_agg(jsonb_build_object('id',n.id,'text',n.text,'seen',n.seen,'matchId',n.match_id,'to',jsonb_build_array(v_actor)) order by n.created_at desc),'[]'::jsonb)
 from club_private.notifications n where n.player_id=v_actor));
end $$;
revoke all on function public.club_snapshot(integer) from public,anon;
grant execute on function public.club_snapshot(integer) to authenticated;

create or replace function public.club_action(p_action text,p_data jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare
 v_actor bigint; v_admin boolean; v_id bigint; v_pid bigint; v_round club_private.rounds%rowtype;
 v_match club_private.matches%rowtype; v_ids jsonb; v_result jsonb; v_entry jsonb;
 v_rating numeric;v_goals integer; v_own integer; v_present boolean; v_season integer; v_turn integer; v_note bigint; v_before jsonb; v_after jsonb; v_subject text; v_actor_name text;
begin
 v_actor:=club_private.actor();
 -- Serialize writes including permission checks: concurrent admins cannot remove the last admin.
 perform pg_advisory_xact_lock(712026);
 select is_admin into v_admin from club_private.members where player_id=v_actor;
 if p_action in ('match','round_open') then v_season:=(p_data->>'season')::integer;
 elsif p_action in ('result','match_cancel','match_edit') then select season into v_season from club_private.matches where id=(p_data->>'id')::bigint;
 elsif p_action in ('vote','round_close','round_final') then select season into v_season from club_private.rounds where id=coalesce(p_data->>'round',p_data->>'id')::bigint;
 end if;
 if p_action in ('match','match_edit','round_open','result','match_cancel','vote','round_close','round_final') and
 not exists(select 1 from club_private.seasons where id=v_season and closed_at is null) then raise exception 'Stagione chiusa: lo storico è consultabile'; end if;
 if p_action='vote' then
  select * into v_round from club_private.rounds where id=(p_data->>'round')::bigint for update;
  if not found or v_round.status<>'open' then raise exception 'Turno non aperto'; end if;
  v_pid:=(p_data->>'candidate')::bigint;
  if v_pid is null or not (v_round.candidates @> jsonb_build_array(v_pid)) then raise exception 'Candidato non ammesso'; end if;
  insert into club_private.ballots(round_id,voter_id,candidate_id) values(v_round.id,v_actor,v_pid);
  -- No audit candidate or ballot timestamp exposed to group admins.
 elsif p_action='seen' then
  update club_private.notifications set seen=true where id=(p_data->>'id')::bigint and player_id=v_actor;
 elsif p_action='push_subscribe' then
  if jsonb_typeof(p_data->'subscription')<>'object' or length((p_data->'subscription')::text)>8192
    or coalesce(p_data->'subscription'->>'endpoint','') !~ '^https://(fcm[.]googleapis[.]com|web[.]push[.]apple[.]com|([a-zA-Z0-9-]+[.])*push[.]services[.]mozilla[.]com|([a-zA-Z0-9-]+[.])+notify[.]windows[.]com)/'
    or not coalesce(p_data->'subscription'->'keys' ?& array['auth','p256dh'],false) then raise exception 'Iscrizione non valida'; end if;
  if (select count(*) from club_private.push_subscriptions where player_id=v_actor)>=5
    and not exists(select 1 from club_private.push_subscriptions where player_id=v_actor and endpoint=p_data->'subscription'->>'endpoint')
    then delete from club_private.push_subscriptions where endpoint=(select endpoint from club_private.push_subscriptions where player_id=v_actor order by created_at limit 1); end if;
  insert into club_private.push_subscriptions(player_id,endpoint,subscription)
   values(v_actor,p_data->'subscription'->>'endpoint',p_data->'subscription')
   on conflict(endpoint) do update set subscription=excluded.subscription where club_private.push_subscriptions.player_id=v_actor;
 else
  if not v_admin then raise exception 'Operazione riservata agli admin'; end if;
  select name into v_actor_name from club_private.players where id=v_actor;
  if p_action in ('match_edit','match_cancel','result') then
   select to_jsonb(m), 'Partita del '||m.match_date::text||' alle '||to_char(m.match_time,'HH24:MI') into v_before,v_subject from club_private.matches m where id=(p_data->>'id')::bigint;
  elsif p_action in ('ratings','player_edit','player_active','player_delete','permission','invite') then
   select to_jsonb(p)-'image_data',p.name into v_before,v_subject from club_private.players p where id=(p_data->>'id')::bigint;
   if p_action='permission' then select to_jsonb(m) into v_before from club_private.members m where player_id=(p_data->>'id')::bigint;end if;
  end if;
  case p_action
  when 'performance_settings' then
   if jsonb_typeof(p_data->'step') is distinct from 'number' then raise exception 'Variazione non valida';end if;
   v_rating:=(p_data->>'step')::numeric;
   if v_rating not in (0,0.5,1) then raise exception 'Seleziona 0, 0,5 oppure 1';end if;
   select jsonb_build_object('step',step) into v_before from club_private.performance_settings where singleton;
   update club_private.performance_settings set step=v_rating where singleton;
   v_after:=jsonb_build_object('step',v_rating);v_subject:='Valutazione prestazioni';
  when 'reminder_settings' then
   if jsonb_typeof(p_data) is distinct from 'object' or not(p_data ?& array['participant_enabled','first_enabled','first_hours','second_enabled','second_hours','result_enabled','match_duration_minutes','result_delay_hours','result_repeat_enabled','result_repeat_hours','result_max_reminders']) then raise exception 'Impostazioni promemoria incomplete'; end if;
   if exists(select 1 from unnest(array['participant_enabled','first_enabled','second_enabled','result_enabled','result_repeat_enabled']) k where jsonb_typeof(p_data->k) is distinct from 'boolean') then raise exception 'Attivazione promemoria non valida'; end if;
   if exists(select 1 from unnest(array['first_hours','second_hours','match_duration_minutes','result_delay_hours','result_repeat_hours','result_max_reminders']) k where jsonb_typeof(p_data->k) is distinct from 'number') then raise exception 'Intervalli promemoria non validi'; end if;
   update club_private.reminder_settings set participant_enabled=(p_data->>'participant_enabled')::boolean,
    first_enabled=(p_data->>'first_enabled')::boolean,first_hours=(p_data->>'first_hours')::numeric,
    second_enabled=(p_data->>'second_enabled')::boolean,second_hours=(p_data->>'second_hours')::numeric,
    result_enabled=(p_data->>'result_enabled')::boolean,match_duration_minutes=(p_data->>'match_duration_minutes')::integer,
    result_delay_hours=(p_data->>'result_delay_hours')::numeric,result_repeat_enabled=(p_data->>'result_repeat_enabled')::boolean,
    result_repeat_hours=(p_data->>'result_repeat_hours')::numeric,result_max_reminders=(p_data->>'result_max_reminders')::integer where singleton;
  when 'season_start' then
   if nullif(trim(p_data->>'name'),'') is null or length(trim(p_data->>'name'))>60 then raise exception 'Nome stagione obbligatorio (massimo 60 caratteri)'; end if;
   if (p_data->>'previous')::integer is distinct from (select id from club_private.seasons where closed_at is null) then raise exception 'Stagione cambiata: aggiorna la pagina'; end if;
   if exists(select 1 from club_private.matches where season=(p_data->>'previous')::integer and cancelled_at is null and result is null) then raise exception 'Registra o annulla prima le partite ancora in programma della stagione attiva'; end if;
   if (p_data->>'started_on')::date is null or (p_data->>'started_on')::date < (select started_on from club_private.seasons where closed_at is null) then raise exception 'Data inizio non valida'; end if;
   select coalesce(max(sid),2025)+1 into v_season from (select id sid from club_private.seasons union select season from club_private.matches union select season from club_private.rounds) known;
   update club_private.rounds set status='closed' where season=(p_data->>'previous')::integer and status='open';
   perform club_private.capture_awards((p_data->>'previous')::integer);
   update club_private.seasons set closed_at=now() where closed_at is null;
   insert into club_private.seasons(id,name,started_on) values(v_season,trim(p_data->>'name'),(p_data->>'started_on')::date);
   v_id:=v_season;
  when 'player_edit' then
   v_pid:=(p_data->>'id')::bigint;
   if not exists(select 1 from club_private.players where id=v_pid) then raise exception 'Giocatore inesistente'; end if;
   if nullif(trim(p_data->>'name'),'') is null or length(trim(p_data->>'name'))>60 then raise exception 'Nome obbligatorio (massimo 60 caratteri)'; end if;
   if (p_data->>'role') is null or (p_data->>'role') not in ('Attaccante','Regista','Difensore','Portiere') then raise exception 'Ruolo non valido'; end if;
   if jsonb_typeof(p_data->'occasional') is distinct from 'boolean' then raise exception 'Tipo di giocatore non valido'; end if;
   if (p_data->>'occasional')::boolean then
    if exists(select 1 from club_private.members where player_id=v_pid and is_admin) then raise exception 'Un admin non può diventare occasionale: rimuovi prima il suo ruolo admin'; end if;
    -- Revoke group access while preserving the player, results and past secret ballots.
    update club_private.push_queue set status='sent',claim_token=null where player_id=v_pid and status<>'sent';
    delete from club_private.push_subscriptions where player_id=v_pid;
    delete from club_private.members where player_id=v_pid;
   end if;
   update club_private.players set name=trim(p_data->>'name'),role=p_data->>'role',occasional=(p_data->>'occasional')::boolean where id=v_pid;
   v_id:=v_pid;
  when 'player_active' then
   v_pid:=(p_data->>'id')::bigint;
   if jsonb_typeof(p_data->'active') is distinct from 'boolean' then raise exception 'Stato non valido'; end if;
   if not exists(select 1 from club_private.players where id=v_pid) then raise exception 'Giocatore inesistente'; end if;
   if not (p_data->>'active')::boolean then
    if exists(select 1 from club_private.members where player_id=v_pid and is_admin) then raise exception 'Rimuovi prima il ruolo admin'; end if;
    if exists(select 1 from club_private.matches where result is null and cancelled_at is null and (team_a @> jsonb_build_array(v_pid) or team_b @> jsonb_build_array(v_pid))) then raise exception 'Rimuovi prima il giocatore dalle partite in programma o annullale'; end if;
    update club_private.push_queue set status='sent',claim_token=null where player_id=v_pid and status<>'sent';
    delete from club_private.push_subscriptions where player_id=v_pid;
   end if;
   update club_private.players set active=(p_data->>'active')::boolean where id=v_pid;
   v_id:=v_pid;
  when 'player_restore' then
   v_pid:=(p_data->>'id')::bigint;
   select profile,profile->>'name' into v_before,v_subject from club_private.deleted_players where player_id=v_pid for update;
   if not found then raise exception 'Giocatore non presente tra gli eliminati'; end if;
   insert into club_private.players(id,name,role,active,occasional,ratings,image_data,default_image) values(v_pid,v_before->>'name',v_before->>'role',coalesce((v_before->>'active')::boolean,true),(v_before->>'occasional')::boolean,v_before->'ratings',v_before->>'image_data',coalesce((v_before->>'default_image')::integer,1));
   if club_private.replay_ratings(v_pid) is not null then update club_private.players set ratings=club_private.replay_ratings(v_pid) where id=v_pid;end if;
   delete from club_private.deleted_players where player_id=v_pid;
   v_id:=v_pid;
  when 'player_delete' then
   v_pid:=(p_data->>'id')::bigint;
   if v_pid=v_actor then raise exception 'Non puoi eliminare il tuo profilo admin'; end if;
   if not exists(select 1 from club_private.players where id=v_pid) then raise exception 'Giocatore inesistente'; end if;
   if exists(select 1 from club_private.matches where cancelled_at is null and result is null and (team_a @> jsonb_build_array(v_pid) or team_b @> jsonb_build_array(v_pid))) then
    raise exception 'Giocatore convocato: annulla prima le partite ancora in programma';
   end if;
   insert into club_private.deleted_players(player_id,profile,deleted_by_name)
    select id,to_jsonb(p),v_actor_name from club_private.players p where id=v_pid;
   delete from club_private.push_queue where player_id=v_pid;
   delete from club_private.notifications where player_id=v_pid;
   delete from club_private.push_subscriptions where player_id=v_pid;
   delete from club_private.ballots where voter_id=v_pid or candidate_id=v_pid;
   update club_private.rounds r set candidates=coalesce((select jsonb_agg(c.value) from jsonb_array_elements(r.candidates) c where c.value<>to_jsonb(v_pid)),'[]'::jsonb)
    where r.candidates @> jsonb_build_array(v_pid);
   delete from club_private.members where player_id=v_pid;
   delete from club_private.players where id=v_pid;
  when 'player' then
   if nullif(trim(p_data->>'name'),'') is null then raise exception 'Nome obbligatorio'; end if;
   if (p_data->>'role') not in ('Attaccante','Regista','Difensore','Portiere') then raise exception 'Ruolo non valido'; end if;
   if coalesce((p_data->>'occasional')::boolean,false) and nullif(trim(p_data->>'email'),'') is not null then raise exception 'Un occasionale non richiede un account'; end if;
   insert into club_private.players(name,role,occasional) values(trim(p_data->>'name'),p_data->>'role',coalesce((p_data->>'occasional')::boolean,false)) returning id into v_id;
   if nullif(trim(p_data->>'email'),'') is not null then
    insert into club_private.members(player_id,email) values(v_id,lower(trim(p_data->>'email')));
   end if;
  when 'invite' then
   v_pid:=(p_data->>'id')::bigint;
   if v_pid=v_actor then raise exception 'Modifica la tua email dalla gestione account, non da questa schermata'; end if;
   if nullif(trim(p_data->>'email'),'') is null then raise exception 'Email obbligatoria'; end if;
   insert into club_private.members(player_id,email) values(v_pid,lower(trim(p_data->>'email')))
    on conflict(player_id) do update set email=excluded.email;
   update club_private.players set occasional=false where id=v_pid;
  when 'ratings' then
   v_ids:=p_data->'ratings';
   if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)<>6 then raise exception 'Servono sei valutazioni'; end if;
   for v_entry in select value from jsonb_array_elements(v_ids) loop
    if jsonb_typeof(v_entry)<>'number' then raise exception 'Valutazione non numerica'; end if;
    v_rating:=v_entry::text::numeric;
    if v_rating<1 or v_rating>99 or v_rating<>round(v_rating,2) then raise exception 'Valutazioni da 1 a 99'; end if;
   end loop;
   update club_private.players set ratings=v_ids where id=(p_data->>'id')::bigint;
   insert into club_private.rating_events(player_id,base_values) values((p_data->>'id')::bigint,v_ids);
  when 'permission' then
   v_pid:=(p_data->>'id')::bigint;
   if p_data->>'key'='admin' then
    if (p_data->>'value')::boolean and exists(select 1 from club_private.players where id=v_pid and not active) then raise exception 'Riattiva prima il giocatore'; end if;
    if v_pid=v_actor then raise exception 'Non puoi rimuovere il tuo ruolo admin'; end if;
    update club_private.members set is_admin=(p_data->>'value')::boolean where player_id=v_pid;
   elsif p_data->>'key'='seeAll' then
    update club_private.members set see_all=(p_data->>'value')::boolean where player_id=v_pid;
   else raise exception 'Permesso non valido'; end if;
   if not found then raise exception 'Collega prima una email al giocatore'; end if;
  when 'match' then
   if jsonb_typeof(p_data->'a')<>'array' or jsonb_typeof(p_data->'b')<>'array' then raise exception 'Squadre obbligatorie'; end if;
   if jsonb_array_length(p_data->'a')<>5 or jsonb_array_length(p_data->'b')<>5 then raise exception 'Servono due squadre da 5'; end if;
   v_ids:=(p_data->'a')||(p_data->'b');
   if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>10 then raise exception 'Servono 10 giocatori distinti'; end if;
   if (select count(*) from club_private.players where active and v_ids @> jsonb_build_array(id))<>10 then raise exception 'Seleziona solo giocatori attivi'; end if;
   v_season:=(p_data->>'season')::integer;
   if (p_data->>'date')::date < (select started_on from club_private.seasons where id=v_season) then raise exception 'Partita precedente all’inizio stagione'; end if;
   insert into club_private.matches(season,match_date,match_time,field,team_a,team_b)
    values(v_season,(p_data->>'date')::date,(p_data->>'time')::time,trim(p_data->>'field'),p_data->'a',p_data->'b') returning id into v_id;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    insert into club_private.notifications(player_id,match_id,text)
     values(v_pid,v_id,'Convocazione: '||(p_data->>'date')||' alle '||(p_data->>'time')||' · '||trim(p_data->>'field')) returning id into v_note;
    insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
   end loop;
  when 'match_edit' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita annullata: dettagli non modificabili'; end if;
   if jsonb_typeof(p_data->'a')<>'array' or jsonb_typeof(p_data->'b')<>'array' then raise exception 'Squadre obbligatorie'; end if;
   if jsonb_array_length(p_data->'a')<>5 or jsonb_array_length(p_data->'b')<>5 then raise exception 'Servono due squadre da 5'; end if;
   v_ids:=(p_data->'a')||(p_data->'b');
   if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>10 then raise exception 'Servono 10 giocatori distinti'; end if;
   if (select count(*) from club_private.players where v_ids @> jsonb_build_array(id))<>10 then raise exception 'Giocatore inesistente'; end if;
   if v_match.result is null and exists(select 1 from club_private.players where not active and v_ids @> jsonb_build_array(id)) then raise exception 'Seleziona solo giocatori attivi'; end if;
   v_season:=v_match.season;
   if (p_data->>'date')::date < (select started_on from club_private.seasons where id=v_season) then raise exception 'Partita precedente all’inizio stagione'; end if;
   if nullif(trim(p_data->>'field'),'') is null or length(trim(p_data->>'field'))>100 then raise exception 'Campo obbligatorio (massimo 100 caratteri)'; end if;
   if (p_data->>'date')::date is null or (p_data->>'time')::time is null then raise exception 'Data e ora obbligatorie'; end if;
   v_result:=null;
   if v_match.result is not null then
    select jsonb_object_agg(pid::text,coalesce(v_match.result->pid::text,jsonb_build_object('goals',0,'own',0,'present',false))) into v_result
    from (select value::text::bigint pid from jsonb_array_elements(v_ids)) ids;
   end if;
   update club_private.matches set match_date=(p_data->>'date')::date,match_time=(p_data->>'time')::time,
    field=trim(p_data->>'field'),team_a=p_data->'a',team_b=p_data->'b',result=v_result,updated_at=now() where id=v_match.id;
   -- Replace obsolete pending messages, then notify retained/new and removed members.
   update club_private.push_queue q set status='sent',claim_token=null from club_private.notifications n
    where q.notification_id=n.id and n.match_id=v_match.id and q.status<>'sent';
   for v_pid in select distinct value::text::bigint from jsonb_array_elements(v_ids||v_match.team_a||v_match.team_b) loop
    if exists(select 1 from club_private.members where player_id=v_pid) then
     insert into club_private.notifications(player_id,match_id,text) values(v_pid,v_match.id,
      case when v_ids @> jsonb_build_array(v_pid) then 'Partita aggiornata: '||(p_data->>'date')||' alle '||(p_data->>'time')||' · '||trim(p_data->>'field')
      else 'Convocazione revocata: partita del '||v_match.match_date::text||' alle '||to_char(v_match.match_time,'HH24:MI') end) returning id into v_note;
     insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
    end if;
   end loop;
   v_id:=v_match.id;
  when 'match_cancel' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita già annullata'; end if;
   if length(coalesce(p_data->>'reason',''))>200 then raise exception 'Motivo troppo lungo'; end if;
   update club_private.matches set cancelled_at=now(),cancellation_reason=nullif(trim(p_data->>'reason'),''),updated_at=now() where id=v_match.id;
   -- Stop queued previous convocations. Already delivered push messages cannot be recalled.
   update club_private.push_queue q set status='sent',claim_token=null
    from club_private.notifications n where q.notification_id=n.id and n.match_id=v_match.id and q.status<>'sent';
   for v_pid in select value::text::bigint from jsonb_array_elements(v_match.team_a||v_match.team_b) where exists(select 1 from club_private.players p where p.id=value::text::bigint) loop
    insert into club_private.notifications(player_id,match_id,text)
     values(v_pid,v_match.id,'Partita annullata: '||v_match.match_date::text||' alle '||to_char(v_match.match_time,'HH24:MI')||' · '||v_match.field||
      case when nullif(trim(p_data->>'reason'),'') is not null then ' · '||trim(p_data->>'reason') else '' end) returning id into v_note;
    insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
   end loop;
  when 'result' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita annullata: tabellino non modificabile'; end if;
   v_ids:=v_match.team_a||v_match.team_b;v_result:=p_data->'result';
   if jsonb_typeof(v_result)<>'object' or (select count(*) from jsonb_object_keys(v_result))<>10 then raise exception 'Tabellino incompleto'; end if;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    v_entry:=v_result->v_pid::text;
    if v_entry is null or not(v_entry ?& array['goals','own','present']) then raise exception 'Tabellino incompleto'; end if;
    if jsonb_typeof(v_entry->'goals')<>'number' or jsonb_typeof(v_entry->'own')<>'number' or jsonb_typeof(v_entry->'present')<>'boolean' then raise exception 'Tipi del tabellino non validi'; end if;
    v_goals:=(v_entry->>'goals')::integer;v_own:=(v_entry->>'own')::integer;v_present:=(v_entry->>'present')::boolean;
    if v_goals is null or v_own is null or v_present is null or v_goals not between 0 and 99 or v_own not between 0 and 99 then raise exception 'Valori non validi'; end if;
    if not v_present and (v_goals>0 or v_own>0) then raise exception 'Un assente non può avere gol'; end if;
    if nullif(v_entry->>'performance','') is not null and (jsonb_typeof(v_entry->'performance')<>'string' or (v_entry->>'performance') not in ('below','same','above')) then raise exception 'Giudizio non valido';end if;
    if not v_present and nullif(v_entry->>'performance','') is not null then raise exception 'Il giudizio vale solo per i presenti';end if;
   end loop;
   update club_private.matches set result=v_result,updated_at=now() where id=v_match.id;
  when 'round_open' then
   v_season:=(p_data->>'season')::integer;
   if v_season is null then raise exception 'Stagione non valida'; end if;
   if (p_data->>'award') not in ('pollone','bidone') then raise exception 'Premio non valido'; end if;
   select * into v_round from club_private.rounds where season=v_season and award=p_data->>'award' order by turn desc limit 1 for update;
   if found then
    if v_round.status='open' then raise exception 'Chiudi il turno precedente'; end if;
    if v_round.status='final' then raise exception 'Premio già assegnato'; end if;
    v_turn:=v_round.turn+1;v_ids:=p_data->'candidates';
    if v_turn>4 then raise exception 'Massimo quattro turni'; end if;
    if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)=0 then raise exception 'Seleziona almeno un candidato'; end if;
    if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>jsonb_array_length(v_ids) then raise exception 'Candidati duplicati'; end if;
    if not(v_round.candidates @> v_ids) then raise exception 'Seleziona solo candidati del turno precedente'; end if;
   else
    v_turn:=1;select jsonb_agg(id order by id) into v_ids from club_private.players;
    if v_ids is null then raise exception 'Aggiungi i giocatori'; end if;
   end if;
   insert into club_private.rounds(season,award,turn,candidates) values(v_season,p_data->>'award',v_turn,v_ids);
  when 'round_close' then
   update club_private.rounds set status='closed' where id=(p_data->>'id')::bigint and status='open';
   if not found then raise exception 'Turno non aperto'; end if;
  when 'round_final' then
   select * into v_round from club_private.rounds where id=(p_data->>'id')::bigint for update;
   if not found or v_round.status<>'closed' then raise exception 'Chiudi prima il turno'; end if;
   if exists(select 1 from club_private.rounds where season=v_round.season and award=v_round.award and turn>v_round.turn) then raise exception 'Esiste un turno successivo'; end if;
   if jsonb_array_length(v_round.candidates)>0 and not exists(select 1 from club_private.ballots where round_id=v_round.id) then raise exception 'Nessun voto ricevuto'; end if;
   update club_private.rounds set status='final' where id=v_round.id;
  else raise exception 'Operazione sconosciuta';
  end case;
  if p_action in ('result','match_cancel','match_edit') then perform club_private.sync_match_ratings((p_data->>'id')::bigint,v_actor);end if;
  if p_action in ('match','match_edit','match_cancel','result') then
   select to_jsonb(m),'Partita del '||m.match_date::text||' alle '||to_char(m.match_time,'HH24:MI') into v_after,v_subject from club_private.matches m where id=coalesce(v_id,(p_data->>'id')::bigint);
  elsif p_action in ('player','player_edit','player_active','player_restore','ratings','invite') then
   select to_jsonb(p)-'image_data',p.name into v_after,v_subject from club_private.players p where id=coalesce(v_id,(p_data->>'id')::bigint);
  elsif p_action='permission' then select to_jsonb(m) into v_after from club_private.members m where player_id=(p_data->>'id')::bigint;
  end if;
  insert into club_private.audit(actor,actor_name,action,subject,details) values(v_actor,v_actor_name,p_action,v_subject,
   case when p_action in ('performance_settings','match','match_edit','match_cancel','result','ratings','player','player_edit','player_active','player_restore','player_delete','permission','invite')
   then jsonb_build_object('before',v_before-'image_data','after',v_after-'image_data') else '{}'::jsonb end);

 end if;
 return jsonb_build_object('ok',true,'id',v_id);
exception when unique_violation then
 raise exception 'Voto già inviato oppure email già associata';
end $$;
revoke all on function public.club_action(text,jsonb) from public,anon;
grant execute on function public.club_action(text,jsonb) to authenticated;

-- Controllo quotidiano: nessun dato personale, nessuna modifica al database.
create function public.club_health() returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object('ok',true)
$$;
revoke all on function public.club_health() from public;
grant execute on function public.club_health() to anon,authenticated;

-- RPC di servizio: solo l'Edge Function può ottenere gli indirizzi push.
create function public.club_claim_push(p_limit integer default 20) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_jobs jsonb;
begin
 perform club_private.enqueue_reminders();
 with chosen as (
  select q.id from club_private.push_queue q
  where q.attempts<3 and (q.status='pending' or (q.status in ('processing','failed') and q.claimed_at<now()-interval '10 minutes'))
  order by q.id limit least(greatest(p_limit,1),20) for update skip locked
 ), claimed as (
  update club_private.push_queue q set status='processing',attempts=attempts+1,claim_token=gen_random_uuid(),claimed_at=now()
  from chosen c where q.id=c.id returning q.*
 )
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'claim',q.claim_token,'body',n.text,
 'subscriptions',(select coalesce(jsonb_agg(s.subscription),'[]'::jsonb) from club_private.push_subscriptions s where s.player_id=q.player_id))),'[]'::jsonb)
 into v_jobs from claimed q join club_private.notifications n on n.id=q.notification_id;
 return v_jobs;
end $$;
revoke all on function public.club_claim_push(integer) from public,anon,authenticated;
grant execute on function public.club_claim_push(integer) to service_role;

create function public.club_ack_push(p_id bigint,p_claim uuid,p_success boolean,p_expired jsonb default '[]'::jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare v_player bigint;
begin
 update club_private.push_queue set status=case when p_success then 'sent' else 'failed' end
 where id=p_id and claim_token=p_claim and status='processing' returning player_id into v_player;
 if not found then raise exception 'Consegna non più assegnata'; end if;
 delete from club_private.push_subscriptions where player_id=v_player and p_expired @> to_jsonb(endpoint);
end $$;
revoke all on function public.club_ack_push(bigint,uuid,boolean,jsonb) from public,anon,authenticated;
grant execute on function public.club_ack_push(bigint,uuid,boolean,jsonb) to service_role;

-- Nessun accesso diretto alle tabelle o alle sequenze da parte del browser.
revoke all on all tables in schema club_private from public,anon,authenticated;
revoke all on all sequences in schema club_private from public,anon,authenticated;

-- Configurazione pubblica push; le chiavi private restano nei Secrets delle Edge Functions.
create table if not exists club_private.push_config (
 singleton boolean primary key default true check(singleton),
 public_key text not null check(public_key ~ '^[A-Za-z0-9_-]{87}$')
);
alter table club_private.push_config enable row level security;
revoke all on club_private.push_config from public,anon,authenticated;
create or replace function public.club_push_config() returns jsonb
language plpgsql security definer set search_path='' as $$
begin
 perform club_private.actor();
 return jsonb_build_object('publicKey',(select public_key from club_private.push_config where singleton));
end $$;
revoke all on function public.club_push_config() from public,anon;
grant execute on function public.club_push_config() to authenticated;

-- Freeze existing closed seasons using the data available today.
do $$
declare sid integer;
begin
 for sid in select id from club_private.seasons where closed_at is not null loop
  perform club_private.capture_awards(sid);
 end loop;
end $$;

-- Funzione tecnica creata dall'opzione Supabase "Enable automatic RLS".
-- Il trigger continua a funzionare con il proprio proprietario; il browser non deve invocarlo.
do $$
begin
 if to_regprocedure('public.rls_auto_enable()') is not null then
  execute 'revoke execute on function public.rls_auto_enable() from public,anon,authenticated';
 end if;
end $$;
-- Stato e disattivazione delle notifiche del solo dispositivo del membro corrente.
create or replace function public.club_device_push(p_endpoint text,p_disable boolean default false)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor bigint:=club_private.actor();
begin
 if p_disable then
  delete from club_private.push_subscriptions where player_id=v_actor and endpoint=p_endpoint;
 end if;
 return jsonb_build_object('active',exists(select 1 from club_private.push_subscriptions where player_id=v_actor and endpoint=p_endpoint));
end;
$$;
revoke all on function public.club_device_push(text,boolean) from public,anon;
grant execute on function public.club_device_push(text,boolean) to authenticated;
-- Le coppie visibili ai membri senza permesso globale comprendono sempre il membro stesso.
create or replace function public.club_pair_statistics(p_season integer default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor bigint:=club_private.actor();v_all boolean;v_data jsonb;
begin
 select is_admin or see_all into v_all from club_private.members where player_id=v_actor;
 if p_season is null then select id into p_season from club_private.seasons where closed_at is null;end if;
 if not exists(select 1 from club_private.seasons where id=p_season) then raise exception 'Stagione non valida';end if;
 with games as (
  select m.*,s.a score_a,s.b score_b from club_private.matches m
  cross join lateral(select
   coalesce(sum(case when m.team_a @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) a,
   coalesce(sum(case when m.team_b @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) b
   from jsonb_each(m.result) e) s
  where m.season=p_season and m.cancelled_at is null and m.result is not null
 ), appearances as (
  select g.id,g.score_a,g.score_b,e.key::bigint pid,g.team_a @> jsonb_build_array(e.key::bigint) side_a
  from games g cross join lateral jsonb_each(g.result) e
  join club_private.players p on p.id=e.key::bigint
  where coalesce((e.value->>'present')::boolean,false)
   and (g.team_a @> jsonb_build_array(e.key::bigint) or g.team_b @> jsonb_build_array(e.key::bigint))
 ), pairs as (
  select a.pid first_id,b.pid second_id,a.side_a=b.side_a together,
   case when a.score_a=a.score_b then 0 when (a.side_a and a.score_a>a.score_b) or (not a.side_a and a.score_b>a.score_a) then 1 else -1 end outcome
  from appearances a join appearances b on a.id=b.id and a.pid<b.pid
  where v_all or a.pid=v_actor or b.pid=v_actor
 ), totals as (
  select first_id,second_id,together,count(*) games,count(*) filter(where outcome=1) wins,
   count(*) filter(where outcome=0) draws,count(*) filter(where outcome=-1) losses
  from pairs group by first_id,second_id,together
 ) select coalesce(jsonb_agg(jsonb_build_object('first',first_id,'second',second_id,'together',together,'games',games,'wins',wins,'draws',draws,'losses',losses) order by together desc,first_id,second_id),'[]'::jsonb) into v_data from totals;
 return jsonb_build_object('pairs',v_data,'ownOnly',not v_all);
end $$;
revoke all on function public.club_pair_statistics(integer) from public,anon;
grant execute on function public.club_pair_statistics(integer) to authenticated;

create or replace function public.club_player_image(p_id bigint,p_image text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor bigint:=club_private.actor();v_name text;v_actor_name text;v_had boolean;
begin
 if not exists(select 1 from club_private.members where player_id=v_actor and is_admin) then raise exception 'Operazione riservata agli admin';end if;
 if p_image is not null and (length(p_image)>1398127 or p_image !~ '^data:image/(png|webp);base64,[A-Za-z0-9+/]+={0,2}$') then raise exception 'Immagine non valida o troppo grande';end if;
 select name,image_data is not null into v_name,v_had from club_private.players where id=p_id for update;
 if not found then raise exception 'Giocatore inesistente';end if;
 update club_private.players set image_data=p_image where id=p_id;
 select name into v_actor_name from club_private.players where id=v_actor;
 insert into club_private.audit(actor,actor_name,action,subject,details) values(v_actor,v_actor_name,'player_image',v_name,jsonb_build_object('before',jsonb_build_object('hasImage',v_had),'after',jsonb_build_object('hasImage',p_image is not null)));
 return jsonb_build_object('ok',true);
end $$;
revoke all on function public.club_player_image(bigint,text) from public,anon;
grant execute on function public.club_player_image(bigint,text) to authenticated;

-- Images are fetched separately in small batches after membership validation.
create or replace function public.club_player_images(p_ids bigint[]) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint:=club_private.actor();v_result jsonb;
begin
 if coalesce(cardinality(p_ids),0)>10 then raise exception 'Richiedi al massimo dieci immagini';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'version',p.image_version,'image',p.image_data)),'[]'::jsonb)
 into v_result from club_private.players p where p.id=any(p_ids) and p.image_data is not null;
 return v_result;
end $$;
revoke all on function public.club_player_images(bigint[]) from public,anon;
grant execute on function public.club_player_images(bigint[]) to authenticated;

create or replace function public.club_player_default_image(p_id bigint,p_default integer)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor bigint:=club_private.actor();v_before jsonb;v_name text;v_actor_name text;
begin
 if not exists(select 1 from club_private.members where player_id=v_actor and is_admin) then raise exception 'Operazione riservata agli admin';end if;
 if p_default is null or p_default not in (1,2) then raise exception 'Immagine predefinita non valida';end if;
 select name,jsonb_build_object('defaultImage',default_image,'hasImage',image_data is not null) into v_name,v_before from club_private.players where id=p_id for update;
 if not found then raise exception 'Giocatore inesistente';end if;
 update club_private.players set default_image=p_default,image_data=null where id=p_id;
 select name into v_actor_name from club_private.players where id=v_actor;
 insert into club_private.audit(actor,actor_name,action,subject,details) values(v_actor,v_actor_name,'player_default_image',v_name,jsonb_build_object('before',v_before,'after',jsonb_build_object('defaultImage',p_default,'hasImage',false)));
 return jsonb_build_object('ok',true);
end $$;
revoke all on function public.club_player_default_image(bigint,integer) from public,anon;
grant execute on function public.club_player_default_image(bigint,integer) to authenticated;

-- Rimozione irreversibile del profilo archiviato; partite e premi storici restano conservati.
create or replace function public.club_player_purge(p_id bigint,p_confirmation text) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint;v_name text;v_actor_name text;
begin
 v_actor:=club_private.actor();
 if not exists(select 1 from club_private.members where player_id=v_actor and is_admin) then
  raise exception 'Operazione riservata agli admin';
 end if;
 if p_confirmation is distinct from 'ELIMINA DEFINITIVAMENTE' then raise exception 'Conferma la rimozione definitiva';end if;
 perform pg_advisory_xact_lock(712026);
 if exists(select 1 from club_private.players where id=p_id) then raise exception 'Il giocatore deve prima essere eliminato';end if;
 select profile->>'name' into v_name from club_private.deleted_players where player_id=p_id for update;
 if not found then raise exception 'Giocatore non presente tra gli eliminati';end if;
 delete from club_private.rating_events where player_id=p_id;
 delete from club_private.deleted_players where player_id=p_id;
 -- Elimina anche eventuali copie dell'immagine nei dettagli dei vecchi audit del profilo.
 update club_private.audit set details=jsonb_set(details,'{before}',(details->'before')-'image_data'-'image')
 where details->'before'->>'id'=p_id::text and jsonb_typeof(details->'before')='object';
 update club_private.audit set details=jsonb_set(details,'{after}',(details->'after')-'image_data'-'image')
 where details->'after'->>'id'=p_id::text and jsonb_typeof(details->'after')='object';
 select name into v_actor_name from club_private.players where id=v_actor;
 insert into club_private.audit(actor,actor_name,action,subject,details)
 values(v_actor,v_actor_name,'player_purge',v_name,jsonb_build_object('playerId',p_id));
 return jsonb_build_object('id',p_id);
end $$;
revoke all on function public.club_player_purge(bigint,text) from public,anon;
grant execute on function public.club_player_purge(bigint,text) to authenticated;
