-- ChickenFutsal: un gruppo privato, stagioni e turni indipendenti per premio.
-- Eseguire una volta nel SQL Editor Supabase. Nessuna tabella è leggibile dal client.
create schema if not exists club_private;
revoke all on schema club_private from public, anon, authenticated;
create table club_private.players (
 id bigint generated by default as identity primary key,
 name text not null check(length(name) between 1 and 60),
 role text not null default 'Regista',
 ratings jsonb not null default '[60,60,60,60,60,60]'::jsonb
);
create table club_private.members (
 player_id bigint primary key references club_private.players(id),
 email text unique not null check(email=lower(email)),
 is_admin boolean not null default false,
 see_all boolean not null default false
);
create table club_private.matches (
 id bigint generated always as identity primary key,
 season integer not null,
 match_date date not null,
 match_time time not null,
 field text not null check(length(field) between 1 and 100),
 team_a jsonb not null, team_b jsonb not null,
 result jsonb, updated_at timestamptz not null default now()
);
create table club_private.rounds (
 id bigint generated always as identity primary key,
 season integer not null,
 award text not null check(award in ('pollone','bidone')),
 turn integer not null check(turn between 1 and 4),
 candidates jsonb not null,
 status text not null default 'open' check(status in ('open','closed','final')),
 unique(season,award,turn)
);
-- Segretezza verso gli admin dell'app; gli operatori del database possono leggere queste tabelle.
create table club_private.ballots (
 round_id bigint not null references club_private.rounds(id),
 voter_id bigint not null references club_private.players(id),
 candidate_id bigint not null references club_private.players(id),
 primary key(round_id,voter_id)
);
create table club_private.notifications (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 match_id bigint not null references club_private.matches(id),
 text text not null, seen boolean not null default false,
 created_at timestamptz not null default now()
);
create table club_private.push_subscriptions (
 player_id bigint not null references club_private.players(id),
 endpoint text primary key, subscription jsonb not null,
 created_at timestamptz not null default now()
);
create table club_private.push_queue (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 notification_id bigint not null references club_private.notifications(id),
 status text not null default 'pending' check(status in ('pending','processing','sent','failed')),
 attempts integer not null default 0,
 claim_token uuid, claimed_at timestamptz, created_at timestamptz not null default now()
);
create table club_private.audit (
 id bigint generated always as identity primary key, actor bigint not null,
 action text not null, created_at timestamptz not null default now()
);
-- Defense in depth. No client policies: access is through checked RPC functions only.
alter table club_private.players enable row level security;
alter table club_private.members enable row level security;
alter table club_private.matches enable row level security;
alter table club_private.rounds enable row level security;
alter table club_private.ballots enable row level security;
alter table club_private.notifications enable row level security;
alter table club_private.push_subscriptions enable row level security;
alter table club_private.push_queue enable row level security;
alter table club_private.audit enable row level security;

create function club_private.actor() returns bigint language plpgsql stable security definer set search_path='' as $$
declare v_id bigint;
begin
 if auth.uid() is null then raise exception 'Accedi al gruppo'; end if;
 select m.player_id into v_id from club_private.members m
 join auth.users u on lower(u.email)=m.email
 where u.id=auth.uid() and u.email_confirmed_at is not null;
 if v_id is null then raise exception 'Account non invitato o email non confermata'; end if;
 return v_id;
end $$;
revoke all on function club_private.actor() from public;

create function public.club_snapshot(p_season integer default 2026) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint; v_admin boolean; v_all boolean; v_players jsonb; v_matches jsonb; v_rounds jsonb;
begin
 v_actor:=club_private.actor();
 if p_season is null or p_season not between 2020 and 2100 then raise exception 'Stagione non valida'; end if;
 select is_admin,see_all into v_admin,v_all from club_private.members where player_id=v_actor;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'role',p.role,
 'admin',coalesce(m.is_admin,false),'seeAll',case when v_admin or p.id=v_actor then coalesce(m.see_all,false) else false end)
 || case when v_admin or v_all or p.id=v_actor then jsonb_build_object('ratings',p.ratings,
 'goals',coalesce(s.goals,0),'own',coalesce(s.own,0),'apps',coalesce(s.apps,0)) else '{}'::jsonb end
 || case when v_admin then jsonb_build_object('email',m.email) else '{}'::jsonb end order by p.id),'[]'::jsonb)
 into v_players from club_private.players p left join club_private.members m on m.player_id=p.id
 left join lateral (
 select sum((r.value->>'goals')::integer) goals,sum((r.value->>'own')::integer) own,
 count(*) filter(where (r.value->>'present')::boolean) apps
 from club_private.matches mm cross join lateral jsonb_each(mm.result) r
 where mm.season=p_season and r.key=p.id::text
 ) s on true;
 select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'date',m.match_date,'time',to_char(m.match_time,'HH24:MI'),
 'field',m.field,'a',m.team_a,'b',m.team_b,'done',m.result is not null,
 'score',case when m.result is null then null else jsonb_build_array(
 (select coalesce(sum(case when m.team_a @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r),
 (select coalesce(sum(case when m.team_b @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r)) end,
 'result',case when v_admin then m.result else null end) order by m.match_date,m.match_time),'[]'::jsonb)
 into v_matches from club_private.matches m where m.season=p_season;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'award',r.award,'turn',r.turn,'status',r.status,'candidates',r.candidates,
 'voted',exists(select 1 from club_private.ballots b where b.round_id=r.id and b.voter_id=v_actor),
 'count',(select count(*) from club_private.ballots b where b.round_id=r.id),
 'results',case when r.status<>'open' then coalesce((select jsonb_agg(jsonb_build_object('id',a.candidate_id,'count',a.n) order by a.n desc,a.candidate_id)
 from (select b.candidate_id,count(*) n from club_private.ballots b where b.round_id=r.id group by b.candidate_id) a),'[]'::jsonb) else '[]'::jsonb end)
 order by r.award,r.turn),'[]'::jsonb) into v_rounds from club_private.rounds r where r.season=p_season;
 return jsonb_build_object('user',v_actor,'season',p_season,'players',v_players,'matches',v_matches,'rounds',v_rounds,
 'seasons',(select coalesce(jsonb_agg(s order by s desc),'[]'::jsonb) from (select season s from club_private.matches union select season from club_private.rounds union select p_season) t),
 'notifications',(select coalesce(jsonb_agg(jsonb_build_object('id',n.id,'text',n.text,'seen',n.seen,'matchId',n.match_id,'to',jsonb_build_array(v_actor)) order by n.created_at desc),'[]'::jsonb)
 from club_private.notifications n where n.player_id=v_actor));
end $$;
revoke all on function public.club_snapshot(integer) from public,anon;
grant execute on function public.club_snapshot(integer) to authenticated;

create function public.club_action(p_action text,p_data jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare
 v_actor bigint; v_admin boolean; v_id bigint; v_pid bigint; v_round club_private.rounds%rowtype;
 v_match club_private.matches%rowtype; v_ids jsonb; v_result jsonb; v_entry jsonb;
 v_goals integer; v_own integer; v_present boolean; v_season integer; v_turn integer; v_note bigint;
begin
 v_actor:=club_private.actor();
 -- Serialize writes including permission checks: concurrent admins cannot remove the last admin.
 perform pg_advisory_xact_lock(712026);
 select is_admin into v_admin from club_private.members where player_id=v_actor;
 if p_action='vote' then
  select * into v_round from club_private.rounds where id=(p_data->>'round')::bigint for update;
  if not found or v_round.status<>'open' then raise exception 'Turno non aperto'; end if;
  v_pid:=(p_data->>'candidate')::bigint;
  if v_pid is null or not (v_round.candidates @> jsonb_build_array(v_pid)) then raise exception 'Candidato non ammesso'; end if;
  insert into club_private.ballots(round_id,voter_id,candidate_id) values(v_round.id,v_actor,v_pid);
  -- No audit candidate or ballot timestamp exposed to group admins.
 elsif p_action='seen' then
  update club_private.notifications set seen=true where id=(p_data->>'id')::bigint and player_id=v_actor;
 elsif p_action='push_subscribe' then
  if jsonb_typeof(p_data->'subscription')<>'object' or length((p_data->'subscription')::text)>8192
    or coalesce(p_data->'subscription'->>'endpoint','') !~ '^https://(fcm[.]googleapis[.]com|web[.]push[.]apple[.]com|([a-zA-Z0-9-]+[.])*push[.]services[.]mozilla[.]com|([a-zA-Z0-9-]+[.])+notify[.]windows[.]com)/'
    or not coalesce(p_data->'subscription'->'keys' ?& array['auth','p256dh'],false) then raise exception 'Iscrizione non valida'; end if;
  if (select count(*) from club_private.push_subscriptions where player_id=v_actor)>=5
    and not exists(select 1 from club_private.push_subscriptions where player_id=v_actor and endpoint=p_data->'subscription'->>'endpoint')
    then delete from club_private.push_subscriptions where endpoint=(select endpoint from club_private.push_subscriptions where player_id=v_actor order by created_at limit 1); end if;
  insert into club_private.push_subscriptions(player_id,endpoint,subscription)
   values(v_actor,p_data->'subscription'->>'endpoint',p_data->'subscription')
   on conflict(endpoint) do update set subscription=excluded.subscription where club_private.push_subscriptions.player_id=v_actor;
 else
  if not v_admin then raise exception 'Operazione riservata agli admin'; end if;
  case p_action
  when 'player' then
   if nullif(trim(p_data->>'name'),'') is null then raise exception 'Nome obbligatorio'; end if;
   if (p_data->>'role') not in ('Attaccante','Regista','Difensore','Portiere') then raise exception 'Ruolo non valido'; end if;
   insert into club_private.players(name,role) values(trim(p_data->>'name'),p_data->>'role') returning id into v_id;
   if nullif(trim(p_data->>'email'),'') is not null then
    insert into club_private.members(player_id,email) values(v_id,lower(trim(p_data->>'email')));
   end if;
  when 'invite' then
   v_pid:=(p_data->>'id')::bigint;
   if v_pid=v_actor then raise exception 'Modifica la tua email dalla gestione account, non da questa schermata'; end if;
   if nullif(trim(p_data->>'email'),'') is null then raise exception 'Email obbligatoria'; end if;
   insert into club_private.members(player_id,email) values(v_pid,lower(trim(p_data->>'email')))
    on conflict(player_id) do update set email=excluded.email;
  when 'ratings' then
   v_ids:=p_data->'ratings';
   if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)<>6 then raise exception 'Servono sei valutazioni'; end if;
   for v_entry in select value from jsonb_array_elements(v_ids) loop
    if jsonb_typeof(v_entry)<>'number' then raise exception 'Valutazione non numerica'; end if;
    v_goals:=v_entry::text::integer;
    if v_goals<1 or v_goals>99 then raise exception 'Valutazioni da 1 a 99'; end if;
   end loop;
   update club_private.players set ratings=v_ids where id=(p_data->>'id')::bigint;
  when 'permission' then
   v_pid:=(p_data->>'id')::bigint;
   if p_data->>'key'='admin' then
    if v_pid=v_actor then raise exception 'Non puoi rimuovere il tuo ruolo admin'; end if;
    update club_private.members set is_admin=(p_data->>'value')::boolean where player_id=v_pid;
   elsif p_data->>'key'='seeAll' then
    update club_private.members set see_all=(p_data->>'value')::boolean where player_id=v_pid;
   else raise exception 'Permesso non valido'; end if;
   if not found then raise exception 'Collega prima una email al giocatore'; end if;
  when 'match' then
   if jsonb_typeof(p_data->'a')<>'array' or jsonb_typeof(p_data->'b')<>'array' then raise exception 'Squadre obbligatorie'; end if;
   if jsonb_array_length(p_data->'a')<>5 or jsonb_array_length(p_data->'b')<>5 then raise exception 'Servono due squadre da 5'; end if;
   v_ids:=(p_data->'a')||(p_data->'b');
   if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>10 then raise exception 'Servono 10 giocatori distinti'; end if;
   if (select count(*) from club_private.players where v_ids @> jsonb_build_array(id))<>10 then raise exception 'Giocatore inesistente'; end if;
   v_season:=(p_data->>'season')::integer;
   if v_season is null or v_season<>extract(year from (p_data->>'date')::date)::integer then raise exception 'Data e stagione non coerenti'; end if;
   insert into club_private.matches(season,match_date,match_time,field,team_a,team_b)
    values(v_season,(p_data->>'date')::date,(p_data->>'time')::time,trim(p_data->>'field'),p_data->'a',p_data->'b') returning id into v_id;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    insert into club_private.notifications(player_id,match_id,text)
     values(v_pid,v_id,'Convocazione: '||(p_data->>'date')||' alle '||(p_data->>'time')||' · '||trim(p_data->>'field')) returning id into v_note;
    insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
   end loop;
  when 'result' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   v_ids:=v_match.team_a||v_match.team_b;v_result:=p_data->'result';
   if jsonb_typeof(v_result)<>'object' or (select count(*) from jsonb_object_keys(v_result))<>10 then raise exception 'Tabellino incompleto'; end if;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    v_entry:=v_result->v_pid::text;
    if v_entry is null or not(v_entry ?& array['goals','own','present']) then raise exception 'Tabellino incompleto'; end if;
    if jsonb_typeof(v_entry->'goals')<>'number' or jsonb_typeof(v_entry->'own')<>'number' or jsonb_typeof(v_entry->'present')<>'boolean' then raise exception 'Tipi del tabellino non validi'; end if;
    v_goals:=(v_entry->>'goals')::integer;v_own:=(v_entry->>'own')::integer;v_present:=(v_entry->>'present')::boolean;
    if v_goals is null or v_own is null or v_present is null or v_goals not between 0 and 99 or v_own not between 0 and 99 then raise exception 'Valori non validi'; end if;
    if not v_present and (v_goals>0 or v_own>0) then raise exception 'Un assente non può avere gol'; end if;
   end loop;
   update club_private.matches set result=v_result,updated_at=now() where id=v_match.id;
  when 'round_open' then
   v_season:=(p_data->>'season')::integer;
   if v_season not between 2020 and 2100 or v_season is null then raise exception 'Stagione non valida'; end if;
   if (p_data->>'award') not in ('pollone','bidone') then raise exception 'Premio non valido'; end if;
   select * into v_round from club_private.rounds where season=v_season and award=p_data->>'award' order by turn desc limit 1 for update;
   if found then
    if v_round.status='open' then raise exception 'Chiudi il turno precedente'; end if;
    if v_round.status='final' then raise exception 'Premio già assegnato'; end if;
    v_turn:=v_round.turn+1;v_ids:=p_data->'candidates';
    if v_turn>4 then raise exception 'Massimo quattro turni'; end if;
    if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)=0 then raise exception 'Seleziona almeno un candidato'; end if;
    if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>jsonb_array_length(v_ids) then raise exception 'Candidati duplicati'; end if;
    if not(v_round.candidates @> v_ids) then raise exception 'Seleziona solo candidati del turno precedente'; end if;
   else
    v_turn:=1;select jsonb_agg(id order by id) into v_ids from club_private.players;
    if v_ids is null then raise exception 'Aggiungi i giocatori'; end if;
   end if;
   insert into club_private.rounds(season,award,turn,candidates) values(v_season,p_data->>'award',v_turn,v_ids);
  when 'round_close' then
   update club_private.rounds set status='closed' where id=(p_data->>'id')::bigint and status='open';
   if not found then raise exception 'Turno non aperto'; end if;
  when 'round_final' then
   select * into v_round from club_private.rounds where id=(p_data->>'id')::bigint for update;
   if not found or v_round.status<>'closed' then raise exception 'Chiudi prima il turno'; end if;
   if exists(select 1 from club_private.rounds where season=v_round.season and award=v_round.award and turn>v_round.turn) then raise exception 'Esiste un turno successivo'; end if;
   if not exists(select 1 from club_private.ballots where round_id=v_round.id) then raise exception 'Nessun voto ricevuto'; end if;
   update club_private.rounds set status='final' where id=v_round.id;
  else raise exception 'Operazione sconosciuta';
  end case;
  insert into club_private.audit(actor,action) values(v_actor,p_action);
 end if;
 return jsonb_build_object('ok',true,'id',v_id);
exception when unique_violation then
 raise exception 'Voto già inviato oppure email già associata';
end $$;
revoke all on function public.club_action(text,jsonb) from public,anon;
grant execute on function public.club_action(text,jsonb) to authenticated;

-- Controllo quotidiano: nessun dato personale, nessuna modifica al database.
create function public.club_health() returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('ok',true,'configured',exists(select 1 from club_private.members))
$$;
revoke all on function public.club_health() from public;
grant execute on function public.club_health() to anon,authenticated;

-- RPC di servizio: solo l'Edge Function può ottenere gli indirizzi push.
create function public.club_claim_push(p_limit integer default 20) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_jobs jsonb;
begin
 with chosen as (
  select q.id from club_private.push_queue q
  where q.attempts<3 and (q.status='pending' or (q.status in ('processing','failed') and q.claimed_at<now()-interval '10 minutes'))
  order by q.id limit least(greatest(p_limit,1),20) for update skip locked
 ), claimed as (
  update club_private.push_queue q set status='processing',attempts=attempts+1,claim_token=gen_random_uuid(),claimed_at=now()
  from chosen c where q.id=c.id returning q.*
 )
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'claim',q.claim_token,'body',n.text,
 'subscriptions',(select coalesce(jsonb_agg(s.subscription),'[]'::jsonb) from club_private.push_subscriptions s where s.player_id=q.player_id))),'[]'::jsonb)
 into v_jobs from claimed q join club_private.notifications n on n.id=q.notification_id;
 return v_jobs;
end $$;
revoke all on function public.club_claim_push(integer) from public,anon,authenticated;
grant execute on function public.club_claim_push(integer) to service_role;

create function public.club_ack_push(p_id bigint,p_claim uuid,p_success boolean,p_expired jsonb default '[]'::jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare v_player bigint;
begin
 update club_private.push_queue set status=case when p_success then 'sent' else 'failed' end
 where id=p_id and claim_token=p_claim and status='processing' returning player_id into v_player;
 if not found then raise exception 'Consegna non più assegnata'; end if;
 delete from club_private.push_subscriptions where player_id=v_player and p_expired @> to_jsonb(endpoint);
end $$;
revoke all on function public.club_ack_push(bigint,uuid,boolean,jsonb) from public,anon,authenticated;
grant execute on function public.club_ack_push(bigint,uuid,boolean,jsonb) to service_role;

-- Nessun accesso diretto alle tabelle o alle sequenze da parte del browser.
revoke all on all tables in schema club_private from public,anon,authenticated;
revoke all on all sequences in schema club_private from public,anon,authenticated;
