-- ChickenFutsal: un gruppo privato, stagioni e turni indipendenti per premio.
-- Eseguire una volta nel SQL Editor Supabase. Nessuna tabella è leggibile dal client.
create schema if not exists club_private;
revoke all on schema club_private from public, anon, authenticated;
create table club_private.players (
 id bigint generated by default as identity primary key,
 name text not null check(length(name) between 1 and 60),
 role text not null default 'Regista',
 occasional boolean not null default false,
 ratings jsonb not null default '[60,60,60,60,60,60]'::jsonb
);
create table club_private.members (
 player_id bigint primary key references club_private.players(id),
 email text unique not null check(email=lower(email)),
 is_admin boolean not null default false,
 see_all boolean not null default false
);
create table club_private.matches (
 id bigint generated always as identity primary key,
 season integer not null,
 match_date date not null,
 match_time time not null,
 field text not null check(length(field) between 1 and 100),
 team_a jsonb not null, team_b jsonb not null,
 cancelled_at timestamptz, cancellation_reason text check(length(cancellation_reason)<=200),
 result jsonb, updated_at timestamptz not null default now()
);
create table club_private.rounds (
 id bigint generated always as identity primary key,
 season integer not null,
 award text not null check(award in ('pollone','bidone')),
 turn integer not null check(turn between 1 and 4),
 candidates jsonb not null,
 status text not null default 'open' check(status in ('open','closed','final')),
 unique(season,award,turn)
);
create table if not exists club_private.seasons (
 id integer primary key, name text not null check(length(name) between 1 and 60),
 started_on date not null, closed_at timestamptz
);
create unique index if not exists one_active_season on club_private.seasons ((true)) where closed_at is null;
insert into club_private.seasons(id,name,started_on,closed_at)
select y,case when y=2026 then '2025/2026' else y::text end,make_date(y,1,1),case when y=max(y) over() then null else now() end
from (select season y from club_private.matches union select season from club_private.rounds union select 2026) t
on conflict(id) do nothing;
alter table club_private.seasons enable row level security;

-- Segretezza verso gli admin dell'app; gli operatori del database possono leggere queste tabelle.
create table club_private.ballots (
 round_id bigint not null references club_private.rounds(id),
 voter_id bigint not null references club_private.players(id),
 candidate_id bigint not null references club_private.players(id),
 primary key(round_id,voter_id)
);
create table club_private.notifications (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 match_id bigint not null references club_private.matches(id),
 text text not null, seen boolean not null default false,
 created_at timestamptz not null default now()
);
create table club_private.push_subscriptions (
 player_id bigint not null references club_private.players(id),
 endpoint text primary key, subscription jsonb not null,
 created_at timestamptz not null default now()
);
create table club_private.push_queue (
 id bigint generated always as identity primary key,
 player_id bigint not null references club_private.players(id),
 notification_id bigint not null references club_private.notifications(id),
 status text not null default 'pending' check(status in ('pending','processing','sent','failed')),
 attempts integer not null default 0,
 claim_token uuid, claimed_at timestamptz, created_at timestamptz not null default now()
);
create table club_private.audit (
 id bigint generated always as identity primary key, actor bigint not null,
 action text not null, created_at timestamptz not null default now()
);
-- Defense in depth. No client policies: access is through checked RPC functions only.
alter table club_private.players enable row level security;
alter table club_private.members enable row level security;
alter table club_private.matches enable row level security;
alter table club_private.rounds enable row level security;
alter table club_private.ballots enable row level security;
alter table club_private.notifications enable row level security;
alter table club_private.push_subscriptions enable row level security;
alter table club_private.push_queue enable row level security;
alter table club_private.audit enable row level security;

create function club_private.actor() returns bigint language plpgsql stable security definer set search_path='' as $$
declare v_id bigint;
begin
 if auth.uid() is null then raise exception 'Accedi al gruppo'; end if;
 select m.player_id into v_id from club_private.members m
 join auth.users u on lower(u.email)=m.email
 where u.id=auth.uid() and u.email_confirmed_at is not null;
 if v_id is null then raise exception 'Account non invitato o email non confermata'; end if;
 return v_id;
end $$;
revoke all on function club_private.actor() from public;

create table if not exists club_private.season_awards (
 season integer primary key references club_private.seasons(id),
 awards jsonb not null, captured_at timestamptz not null default now()
);
alter table club_private.season_awards enable row level security;
revoke all on club_private.season_awards from public,anon,authenticated;
-- This function is private: closure calls it inside the same transaction.
create or replace function club_private.capture_awards(p_season integer) returns void
language plpgsql security definer set search_path='' as $$
declare v_awards jsonb; v_award text; v_winners jsonb;
begin
 if exists(select 1 from club_private.season_awards where season=p_season) then return; end if;
  with totals as (
   select p.id,p.name,coalesce(sum((r.value->>'goals')::int),0) goals,
    coalesce(sum((r.value->>'own')::int),0) own,
    count(*) filter(where (r.value->>'present')::boolean) apps
   from club_private.players p left join club_private.matches m on m.season=p_season and m.cancelled_at is null and m.result ? p.id::text
   left join lateral jsonb_each(m.result) r on r.key=p.id::text group by p.id,p.name
  ), scores as (
   select t.id,t.name,v.metric,v.total from totals t cross join lateral (values ('goals',t.goals),('own',t.own),('apps',t.apps)) v(metric,total)
  ), ranked as (
   select *,max(total) over(partition by metric) maximum from scores
  ), winners as (
   select metric,jsonb_agg(jsonb_build_object('id',id,'name',name) order by id) identities from ranked where total=maximum and maximum>0 group by metric
  ) select coalesce(jsonb_object_agg(metric,identities),'{}'::jsonb) into v_awards from winners;
 v_awards:=jsonb_build_object('goals','[]'::jsonb,'own','[]'::jsonb,'apps','[]'::jsonb)||v_awards;
 foreach v_award in array array['pollone','bidone'] loop
  with latest as (
   select id,status from club_private.rounds where season=p_season and award=v_award order by turn desc limit 1
  ), counts as (
   select p.id,p.name,count(*) votes from latest r join club_private.ballots b on b.round_id=r.id
   join club_private.players p on p.id=b.candidate_id where r.status='final' group by p.id,p.name
  ) select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name) order by id),'[]'::jsonb)
   into v_winners from counts where votes=(select max(votes) from counts);
  v_awards:=v_awards||jsonb_build_object(v_award,v_winners);
 end loop;
 insert into club_private.season_awards(season,awards) values(p_season,v_awards) on conflict(season) do nothing;
end $$;
revoke all on function club_private.capture_awards(integer) from public,anon,authenticated;

create function public.club_snapshot(p_season integer default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_actor bigint; v_admin boolean; v_all boolean; v_players jsonb; v_matches jsonb; v_rounds jsonb; v_awards jsonb;
begin
 v_actor:=club_private.actor();
 if p_season is null then select id into p_season from club_private.seasons where closed_at is null; end if;
 if not exists(select 1 from club_private.seasons where id=p_season) then raise exception 'Stagione non valida'; end if;
 select is_admin,see_all into v_admin,v_all from club_private.members where player_id=v_actor;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'role',p.role,
 'occasional',p.occasional,'admin',coalesce(m.is_admin,false),'seeAll',case when v_admin or p.id=v_actor then coalesce(m.see_all,false) else false end)
 || case when v_admin or v_all or p.id=v_actor then jsonb_build_object('ratings',p.ratings,
 'goals',coalesce(s.goals,0),'own',coalesce(s.own,0),'apps',coalesce(s.apps,0),
 'wins',coalesce(s.wins,0),'draws',coalesce(s.draws,0),'losses',coalesce(s.losses,0),
 'winRate',case when s.apps>0 then round(100.0*s.wins/s.apps,2) else 0 end,
 'goalAverage',case when s.apps>0 then round(s.goals::numeric/s.apps,2) else 0 end) else '{}'::jsonb end
 || case when v_admin then jsonb_build_object('email',m.email) else '{}'::jsonb end order by p.id),'[]'::jsonb)
 into v_players from club_private.players p left join club_private.members m on m.player_id=p.id
 left join lateral (
 select sum((r.value->>'goals')::integer) goals,sum((r.value->>'own')::integer) own,
 count(*) filter(where (r.value->>'present')::boolean) apps,
 count(*) filter(where (r.value->>'present')::boolean and
  case when mm.team_a @> jsonb_build_array(p.id) then score.a>score.b else score.b>score.a end) wins,
 count(*) filter(where (r.value->>'present')::boolean and score.a=score.b) draws,
 count(*) filter(where (r.value->>'present')::boolean and
  case when mm.team_a @> jsonb_build_array(p.id) then score.a<score.b else score.b<score.a end) losses
 from club_private.matches mm cross join lateral jsonb_each(mm.result) r
 cross join lateral (
  select coalesce(sum(case when mm.team_a @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) a,
   coalesce(sum(case when mm.team_b @> jsonb_build_array(e.key::bigint) then (e.value->>'goals')::int else (e.value->>'own')::int end),0) b
  from jsonb_each(mm.result) e
 ) score
 where mm.season=p_season and mm.cancelled_at is null and r.key=p.id::text
 ) s on true;
 select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'date',m.match_date,'time',to_char(m.match_time,'HH24:MI'),
 'field',m.field,'cancelled',m.cancelled_at is not null,'cancellationReason',m.cancellation_reason,'a',m.team_a,'b',m.team_b,'done',m.result is not null,
 'score',case when m.result is null then null else jsonb_build_array(
 (select coalesce(sum(case when m.team_a @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r),
 (select coalesce(sum(case when m.team_b @> jsonb_build_array(r.key::bigint) then (r.value->>'goals')::int else (r.value->>'own')::int end),0) from jsonb_each(m.result) r)) end,
 'result',case when v_admin then m.result else null end) order by m.match_date,m.match_time),'[]'::jsonb)
 into v_matches from club_private.matches m where m.season=p_season;
 select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'award',r.award,'turn',r.turn,'status',r.status,'candidates',r.candidates,
 'voted',exists(select 1 from club_private.ballots b where b.round_id=r.id and b.voter_id=v_actor),
 'count',(select count(*) from club_private.ballots b where b.round_id=r.id),
 'results',case when r.status<>'open' then coalesce((select jsonb_agg(jsonb_build_object('id',a.candidate_id,'count',a.n) order by a.n desc,a.candidate_id)
 from (select b.candidate_id,count(*) n from club_private.ballots b where b.round_id=r.id group by b.candidate_id) a),'[]'::jsonb) else '[]'::jsonb end)
 order by r.award,r.turn),'[]'::jsonb) into v_rounds from club_private.rounds r where r.season=p_season;
 v_awards:=coalesce((select awards from club_private.season_awards where season=p_season),'{}'::jsonb);
 return jsonb_build_object('user',v_actor,'season',p_season,'players',v_players,'matches',v_matches,'rounds',v_rounds,
 'closedAwards',v_awards,
 'hallOfFame',(select coalesce(jsonb_agg(jsonb_build_object('season',s.id,'name',s.name,'closedAt',s.closed_at,'awards',a.awards) order by s.id desc),'[]'::jsonb) from club_private.seasons s join club_private.season_awards a on a.season=s.id where s.closed_at is not null),
 'activeSeason',(select id from club_private.seasons where closed_at is null),
 'seasonInfo',(select to_jsonb(s) from club_private.seasons s where id=p_season),
 'seasons',(select jsonb_agg(id order by id desc) from club_private.seasons),
 'seasonOptions',(select jsonb_agg(to_jsonb(s) order by id desc) from club_private.seasons s),
 'notifications',(select coalesce(jsonb_agg(jsonb_build_object('id',n.id,'text',n.text,'seen',n.seen,'matchId',n.match_id,'to',jsonb_build_array(v_actor)) order by n.created_at desc),'[]'::jsonb)
 from club_private.notifications n where n.player_id=v_actor));
end $$;
revoke all on function public.club_snapshot(integer) from public,anon;
grant execute on function public.club_snapshot(integer) to authenticated;

create function public.club_action(p_action text,p_data jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare
 v_actor bigint; v_admin boolean; v_id bigint; v_pid bigint; v_round club_private.rounds%rowtype;
 v_match club_private.matches%rowtype; v_ids jsonb; v_result jsonb; v_entry jsonb;
 v_goals integer; v_own integer; v_present boolean; v_season integer; v_turn integer; v_note bigint;
begin
 v_actor:=club_private.actor();
 -- Serialize writes including permission checks: concurrent admins cannot remove the last admin.
 perform pg_advisory_xact_lock(712026);
 select is_admin into v_admin from club_private.members where player_id=v_actor;
 if p_action in ('match','round_open') then v_season:=(p_data->>'season')::integer;
 elsif p_action in ('result','match_cancel','match_edit') then select season into v_season from club_private.matches where id=(p_data->>'id')::bigint;
 elsif p_action in ('vote','round_close','round_final') then select season into v_season from club_private.rounds where id=coalesce(p_data->>'round',p_data->>'id')::bigint;
 end if;
 if p_action in ('match','match_edit','round_open','result','match_cancel','vote','round_close','round_final') and
 not exists(select 1 from club_private.seasons where id=v_season and closed_at is null) then raise exception 'Stagione chiusa: lo storico è consultabile'; end if;
 if p_action='vote' then
  select * into v_round from club_private.rounds where id=(p_data->>'round')::bigint for update;
  if not found or v_round.status<>'open' then raise exception 'Turno non aperto'; end if;
  v_pid:=(p_data->>'candidate')::bigint;
  if v_pid is null or not (v_round.candidates @> jsonb_build_array(v_pid)) then raise exception 'Candidato non ammesso'; end if;
  insert into club_private.ballots(round_id,voter_id,candidate_id) values(v_round.id,v_actor,v_pid);
  -- No audit candidate or ballot timestamp exposed to group admins.
 elsif p_action='seen' then
  update club_private.notifications set seen=true where id=(p_data->>'id')::bigint and player_id=v_actor;
 elsif p_action='push_subscribe' then
  if jsonb_typeof(p_data->'subscription')<>'object' or length((p_data->'subscription')::text)>8192
    or coalesce(p_data->'subscription'->>'endpoint','') !~ '^https://(fcm[.]googleapis[.]com|web[.]push[.]apple[.]com|([a-zA-Z0-9-]+[.])*push[.]services[.]mozilla[.]com|([a-zA-Z0-9-]+[.])+notify[.]windows[.]com)/'
    or not coalesce(p_data->'subscription'->'keys' ?& array['auth','p256dh'],false) then raise exception 'Iscrizione non valida'; end if;
  if (select count(*) from club_private.push_subscriptions where player_id=v_actor)>=5
    and not exists(select 1 from club_private.push_subscriptions where player_id=v_actor and endpoint=p_data->'subscription'->>'endpoint')
    then delete from club_private.push_subscriptions where endpoint=(select endpoint from club_private.push_subscriptions where player_id=v_actor order by created_at limit 1); end if;
  insert into club_private.push_subscriptions(player_id,endpoint,subscription)
   values(v_actor,p_data->'subscription'->>'endpoint',p_data->'subscription')
   on conflict(endpoint) do update set subscription=excluded.subscription where club_private.push_subscriptions.player_id=v_actor;
 else
  if not v_admin then raise exception 'Operazione riservata agli admin'; end if;
  case p_action
  when 'season_start' then
   if nullif(trim(p_data->>'name'),'') is null or length(trim(p_data->>'name'))>60 then raise exception 'Nome stagione obbligatorio (massimo 60 caratteri)'; end if;
   if (p_data->>'previous')::integer is distinct from (select id from club_private.seasons where closed_at is null) then raise exception 'Stagione cambiata: aggiorna la pagina'; end if;
   if exists(select 1 from club_private.matches where season=(p_data->>'previous')::integer and cancelled_at is null and result is null) then raise exception 'Registra o annulla prima le partite ancora in programma della stagione attiva'; end if;
   if (p_data->>'started_on')::date is null or (p_data->>'started_on')::date < (select started_on from club_private.seasons where closed_at is null) then raise exception 'Data inizio non valida'; end if;
   select coalesce(max(sid),2025)+1 into v_season from (select id sid from club_private.seasons union select season from club_private.matches union select season from club_private.rounds) known;
   update club_private.rounds set status='closed' where season=(p_data->>'previous')::integer and status='open';
   perform club_private.capture_awards((p_data->>'previous')::integer);
   update club_private.seasons set closed_at=now() where closed_at is null;
   insert into club_private.seasons(id,name,started_on) values(v_season,trim(p_data->>'name'),(p_data->>'started_on')::date);
   v_id:=v_season;
  when 'player_delete' then
   v_pid:=(p_data->>'id')::bigint;
   if v_pid=v_actor then raise exception 'Non puoi eliminare il tuo profilo admin'; end if;
   if not exists(select 1 from club_private.players where id=v_pid) then raise exception 'Giocatore inesistente'; end if;
   if exists(select 1 from club_private.matches where cancelled_at is null and result is null and (team_a @> jsonb_build_array(v_pid) or team_b @> jsonb_build_array(v_pid))) then
    raise exception 'Giocatore convocato: annulla prima le partite ancora in programma';
   end if;
   delete from club_private.push_queue where player_id=v_pid;
   delete from club_private.notifications where player_id=v_pid;
   delete from club_private.push_subscriptions where player_id=v_pid;
   delete from club_private.ballots where voter_id=v_pid or candidate_id=v_pid;
   update club_private.rounds r set candidates=coalesce((select jsonb_agg(c.value) from jsonb_array_elements(r.candidates) c where c.value<>to_jsonb(v_pid)),'[]'::jsonb)
    where r.candidates @> jsonb_build_array(v_pid);
   delete from club_private.members where player_id=v_pid;
   delete from club_private.players where id=v_pid;
  when 'player' then
   if nullif(trim(p_data->>'name'),'') is null then raise exception 'Nome obbligatorio'; end if;
   if (p_data->>'role') not in ('Attaccante','Regista','Difensore','Portiere') then raise exception 'Ruolo non valido'; end if;
   if coalesce((p_data->>'occasional')::boolean,false) and nullif(trim(p_data->>'email'),'') is not null then raise exception 'Un occasionale non richiede un account'; end if;
   insert into club_private.players(name,role,occasional) values(trim(p_data->>'name'),p_data->>'role',coalesce((p_data->>'occasional')::boolean,false)) returning id into v_id;
   if nullif(trim(p_data->>'email'),'') is not null then
    insert into club_private.members(player_id,email) values(v_id,lower(trim(p_data->>'email')));
   end if;
  when 'invite' then
   v_pid:=(p_data->>'id')::bigint;
   if v_pid=v_actor then raise exception 'Modifica la tua email dalla gestione account, non da questa schermata'; end if;
   if nullif(trim(p_data->>'email'),'') is null then raise exception 'Email obbligatoria'; end if;
   insert into club_private.members(player_id,email) values(v_pid,lower(trim(p_data->>'email')))
    on conflict(player_id) do update set email=excluded.email;
   update club_private.players set occasional=false where id=v_pid;
  when 'ratings' then
   v_ids:=p_data->'ratings';
   if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)<>6 then raise exception 'Servono sei valutazioni'; end if;
   for v_entry in select value from jsonb_array_elements(v_ids) loop
    if jsonb_typeof(v_entry)<>'number' then raise exception 'Valutazione non numerica'; end if;
    v_goals:=v_entry::text::integer;
    if v_goals<1 or v_goals>99 then raise exception 'Valutazioni da 1 a 99'; end if;
   end loop;
   update club_private.players set ratings=v_ids where id=(p_data->>'id')::bigint;
  when 'permission' then
   v_pid:=(p_data->>'id')::bigint;
   if p_data->>'key'='admin' then
    if v_pid=v_actor then raise exception 'Non puoi rimuovere il tuo ruolo admin'; end if;
    update club_private.members set is_admin=(p_data->>'value')::boolean where player_id=v_pid;
   elsif p_data->>'key'='seeAll' then
    update club_private.members set see_all=(p_data->>'value')::boolean where player_id=v_pid;
   else raise exception 'Permesso non valido'; end if;
   if not found then raise exception 'Collega prima una email al giocatore'; end if;
  when 'match' then
   if jsonb_typeof(p_data->'a')<>'array' or jsonb_typeof(p_data->'b')<>'array' then raise exception 'Squadre obbligatorie'; end if;
   if jsonb_array_length(p_data->'a')<>5 or jsonb_array_length(p_data->'b')<>5 then raise exception 'Servono due squadre da 5'; end if;
   v_ids:=(p_data->'a')||(p_data->'b');
   if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>10 then raise exception 'Servono 10 giocatori distinti'; end if;
   if (select count(*) from club_private.players where v_ids @> jsonb_build_array(id))<>10 then raise exception 'Giocatore inesistente'; end if;
   v_season:=(p_data->>'season')::integer;
   if (p_data->>'date')::date < (select started_on from club_private.seasons where id=v_season) then raise exception 'Partita precedente all’inizio stagione'; end if;
   insert into club_private.matches(season,match_date,match_time,field,team_a,team_b)
    values(v_season,(p_data->>'date')::date,(p_data->>'time')::time,trim(p_data->>'field'),p_data->'a',p_data->'b') returning id into v_id;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    insert into club_private.notifications(player_id,match_id,text)
     values(v_pid,v_id,'Convocazione: '||(p_data->>'date')||' alle '||(p_data->>'time')||' · '||trim(p_data->>'field')) returning id into v_note;
    insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
   end loop;
  when 'match_edit' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita annullata: dettagli non modificabili'; end if;
   if jsonb_typeof(p_data->'a')<>'array' or jsonb_typeof(p_data->'b')<>'array' then raise exception 'Squadre obbligatorie'; end if;
   if jsonb_array_length(p_data->'a')<>5 or jsonb_array_length(p_data->'b')<>5 then raise exception 'Servono due squadre da 5'; end if;
   v_ids:=(p_data->'a')||(p_data->'b');
   if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>10 then raise exception 'Servono 10 giocatori distinti'; end if;
   if (select count(*) from club_private.players where v_ids @> jsonb_build_array(id))<>10 then raise exception 'Giocatore inesistente'; end if;
   v_season:=v_match.season;
   if (p_data->>'date')::date < (select started_on from club_private.seasons where id=v_season) then raise exception 'Partita precedente all’inizio stagione'; end if;
   if nullif(trim(p_data->>'field'),'') is null or length(trim(p_data->>'field'))>100 then raise exception 'Campo obbligatorio (massimo 100 caratteri)'; end if;
   if (p_data->>'date')::date is null or (p_data->>'time')::time is null then raise exception 'Data e ora obbligatorie'; end if;
   v_result:=null;
   if v_match.result is not null then
    select jsonb_object_agg(pid::text,coalesce(v_match.result->pid::text,jsonb_build_object('goals',0,'own',0,'present',false))) into v_result
    from (select value::text::bigint pid from jsonb_array_elements(v_ids)) ids;
   end if;
   update club_private.matches set match_date=(p_data->>'date')::date,match_time=(p_data->>'time')::time,
    field=trim(p_data->>'field'),team_a=p_data->'a',team_b=p_data->'b',result=v_result,updated_at=now() where id=v_match.id;
   -- Replace obsolete pending messages, then notify retained/new and removed members.
   update club_private.push_queue q set status='sent',claim_token=null from club_private.notifications n
    where q.notification_id=n.id and n.match_id=v_match.id and q.status<>'sent';
   for v_pid in select distinct value::text::bigint from jsonb_array_elements(v_ids||v_match.team_a||v_match.team_b) loop
    if exists(select 1 from club_private.members where player_id=v_pid) then
     insert into club_private.notifications(player_id,match_id,text) values(v_pid,v_match.id,
      case when v_ids @> jsonb_build_array(v_pid) then 'Partita aggiornata: '||(p_data->>'date')||' alle '||(p_data->>'time')||' · '||trim(p_data->>'field')
      else 'Convocazione revocata: partita del '||v_match.match_date::text||' alle '||to_char(v_match.match_time,'HH24:MI') end) returning id into v_note;
     insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
    end if;
   end loop;
   v_id:=v_match.id;
  when 'match_cancel' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita già annullata'; end if;
   if length(coalesce(p_data->>'reason',''))>200 then raise exception 'Motivo troppo lungo'; end if;
   update club_private.matches set cancelled_at=now(),cancellation_reason=nullif(trim(p_data->>'reason'),''),updated_at=now() where id=v_match.id;
   -- Stop queued previous convocations. Already delivered push messages cannot be recalled.
   update club_private.push_queue q set status='sent',claim_token=null
    from club_private.notifications n where q.notification_id=n.id and n.match_id=v_match.id and q.status<>'sent';
   for v_pid in select value::text::bigint from jsonb_array_elements(v_match.team_a||v_match.team_b) loop
    insert into club_private.notifications(player_id,match_id,text)
     values(v_pid,v_match.id,'Partita annullata: '||v_match.match_date::text||' alle '||to_char(v_match.match_time,'HH24:MI')||' · '||v_match.field||
      case when nullif(trim(p_data->>'reason'),'') is not null then ' · '||trim(p_data->>'reason') else '' end) returning id into v_note;
    insert into club_private.push_queue(player_id,notification_id) values(v_pid,v_note);
   end loop;
  when 'result' then
   select * into v_match from club_private.matches where id=(p_data->>'id')::bigint for update;
   if not found then raise exception 'Partita inesistente'; end if;
   if v_match.cancelled_at is not null then raise exception 'Partita annullata: tabellino non modificabile'; end if;
   v_ids:=v_match.team_a||v_match.team_b;v_result:=p_data->'result';
   if jsonb_typeof(v_result)<>'object' or (select count(*) from jsonb_object_keys(v_result))<>10 then raise exception 'Tabellino incompleto'; end if;
   for v_pid in select value::text::bigint from jsonb_array_elements(v_ids) loop
    v_entry:=v_result->v_pid::text;
    if v_entry is null or not(v_entry ?& array['goals','own','present']) then raise exception 'Tabellino incompleto'; end if;
    if jsonb_typeof(v_entry->'goals')<>'number' or jsonb_typeof(v_entry->'own')<>'number' or jsonb_typeof(v_entry->'present')<>'boolean' then raise exception 'Tipi del tabellino non validi'; end if;
    v_goals:=(v_entry->>'goals')::integer;v_own:=(v_entry->>'own')::integer;v_present:=(v_entry->>'present')::boolean;
    if v_goals is null or v_own is null or v_present is null or v_goals not between 0 and 99 or v_own not between 0 and 99 then raise exception 'Valori non validi'; end if;
    if not v_present and (v_goals>0 or v_own>0) then raise exception 'Un assente non può avere gol'; end if;
   end loop;
   update club_private.matches set result=v_result,updated_at=now() where id=v_match.id;
  when 'round_open' then
   v_season:=(p_data->>'season')::integer;
   if v_season is null then raise exception 'Stagione non valida'; end if;
   if (p_data->>'award') not in ('pollone','bidone') then raise exception 'Premio non valido'; end if;
   select * into v_round from club_private.rounds where season=v_season and award=p_data->>'award' order by turn desc limit 1 for update;
   if found then
    if v_round.status='open' then raise exception 'Chiudi il turno precedente'; end if;
    if v_round.status='final' then raise exception 'Premio già assegnato'; end if;
    v_turn:=v_round.turn+1;v_ids:=p_data->'candidates';
    if v_turn>4 then raise exception 'Massimo quattro turni'; end if;
    if jsonb_typeof(v_ids)<>'array' or jsonb_array_length(v_ids)=0 then raise exception 'Seleziona almeno un candidato'; end if;
    if (select count(distinct value::text::bigint) from jsonb_array_elements(v_ids))<>jsonb_array_length(v_ids) then raise exception 'Candidati duplicati'; end if;
    if not(v_round.candidates @> v_ids) then raise exception 'Seleziona solo candidati del turno precedente'; end if;
   else
    v_turn:=1;select jsonb_agg(id order by id) into v_ids from club_private.players;
    if v_ids is null then raise exception 'Aggiungi i giocatori'; end if;
   end if;
   insert into club_private.rounds(season,award,turn,candidates) values(v_season,p_data->>'award',v_turn,v_ids);
  when 'round_close' then
   update club_private.rounds set status='closed' where id=(p_data->>'id')::bigint and status='open';
   if not found then raise exception 'Turno non aperto'; end if;
  when 'round_final' then
   select * into v_round from club_private.rounds where id=(p_data->>'id')::bigint for update;
   if not found or v_round.status<>'closed' then raise exception 'Chiudi prima il turno'; end if;
   if exists(select 1 from club_private.rounds where season=v_round.season and award=v_round.award and turn>v_round.turn) then raise exception 'Esiste un turno successivo'; end if;
   if jsonb_array_length(v_round.candidates)>0 and not exists(select 1 from club_private.ballots where round_id=v_round.id) then raise exception 'Nessun voto ricevuto'; end if;
   update club_private.rounds set status='final' where id=v_round.id;
  else raise exception 'Operazione sconosciuta';
  end case;
  insert into club_private.audit(actor,action) values(v_actor,p_action);
 end if;
 return jsonb_build_object('ok',true,'id',v_id);
exception when unique_violation then
 raise exception 'Voto già inviato oppure email già associata';
end $$;
revoke all on function public.club_action(text,jsonb) from public,anon;
grant execute on function public.club_action(text,jsonb) to authenticated;

-- Controllo quotidiano: nessun dato personale, nessuna modifica al database.
create function public.club_health() returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object('ok',true)
$$;
revoke all on function public.club_health() from public;
grant execute on function public.club_health() to anon,authenticated;

-- RPC di servizio: solo l'Edge Function può ottenere gli indirizzi push.
create function public.club_claim_push(p_limit integer default 20) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_jobs jsonb;
begin
 with chosen as (
  select q.id from club_private.push_queue q
  where q.attempts<3 and (q.status='pending' or (q.status in ('processing','failed') and q.claimed_at<now()-interval '10 minutes'))
  order by q.id limit least(greatest(p_limit,1),20) for update skip locked
 ), claimed as (
  update club_private.push_queue q set status='processing',attempts=attempts+1,claim_token=gen_random_uuid(),claimed_at=now()
  from chosen c where q.id=c.id returning q.*
 )
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'claim',q.claim_token,'body',n.text,
 'subscriptions',(select coalesce(jsonb_agg(s.subscription),'[]'::jsonb) from club_private.push_subscriptions s where s.player_id=q.player_id))),'[]'::jsonb)
 into v_jobs from claimed q join club_private.notifications n on n.id=q.notification_id;
 return v_jobs;
end $$;
revoke all on function public.club_claim_push(integer) from public,anon,authenticated;
grant execute on function public.club_claim_push(integer) to service_role;

create function public.club_ack_push(p_id bigint,p_claim uuid,p_success boolean,p_expired jsonb default '[]'::jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare v_player bigint;
begin
 update club_private.push_queue set status=case when p_success then 'sent' else 'failed' end
 where id=p_id and claim_token=p_claim and status='processing' returning player_id into v_player;
 if not found then raise exception 'Consegna non più assegnata'; end if;
 delete from club_private.push_subscriptions where player_id=v_player and p_expired @> to_jsonb(endpoint);
end $$;
revoke all on function public.club_ack_push(bigint,uuid,boolean,jsonb) from public,anon,authenticated;
grant execute on function public.club_ack_push(bigint,uuid,boolean,jsonb) to service_role;

-- Nessun accesso diretto alle tabelle o alle sequenze da parte del browser.
revoke all on all tables in schema club_private from public,anon,authenticated;
revoke all on all sequences in schema club_private from public,anon,authenticated;

-- Configurazione pubblica push; le chiavi private restano nei Secrets delle Edge Functions.
create table if not exists club_private.push_config (
 singleton boolean primary key default true check(singleton),
 public_key text not null check(public_key ~ '^[A-Za-z0-9_-]{87}$')
);
alter table club_private.push_config enable row level security;
revoke all on club_private.push_config from public,anon,authenticated;
create or replace function public.club_push_config() returns jsonb
language plpgsql security definer set search_path='' as $$
begin
 perform club_private.actor();
 return jsonb_build_object('publicKey',(select public_key from club_private.push_config where singleton));
end $$;
revoke all on function public.club_push_config() from public,anon;
grant execute on function public.club_push_config() to authenticated;

-- Freeze existing closed seasons using the data available today.
do $$
declare sid integer;
begin
 for sid in select id from club_private.seasons where closed_at is not null loop
  perform club_private.capture_awards(sid);
 end loop;
end $$;

-- Funzione tecnica creata dall'opzione Supabase "Enable automatic RLS".
-- Il trigger continua a funzionare con il proprio proprietario; il browser non deve invocarlo.
do $$
begin
 if to_regprocedure('public.rls_auto_enable()') is not null then
  execute 'revoke execute on function public.rls_auto_enable() from public,anon,authenticated';
 end if;
end $$;
