import { PGlite } from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated;create role service_role; create role supabase_auth_admin;
create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.test_uid',true),'')::uuid$$;`);
await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_cancel_matches_and_guests.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_delete_player.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_invite_only_signup.sql',import.meta.url),'utf8'));
for(let i=1;i<=12;i++){
 await db.query(`insert into club_private.players(id,name,role) values($1,$2,'Regista')`,[i,'Player '+i]);
 await db.query(`insert into club_private.members(player_id,email,is_admin,see_all) values($1,$2,$3,false)`,[i,`p${i}@test.invalid`,i===1]);
 await db.query(`insert into auth.users values($1,$2,now())`,[`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`,`p${i}@test.invalid`]);
}
await db.exec(`select setval(pg_get_serial_sequence('club_private.players','id'),12,true)`);
async function as(i,role='authenticated'){
 await db.exec('reset role');await db.query(`select set_config('request.test_uid',$1,false)`,[`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`]);await db.exec(`set role ${role}`);
}
const act=async (action,data)=> (await db.query('select public.club_action($1,$2::jsonb) result',[action,JSON.stringify(data)])).rows[0].result;
const snapshot=async (season=2026)=>(await db.query('select public.club_snapshot($1) result',[season])).rows[0].result;
async function rejects(fn){await assert.rejects(fn)}
await as(1,'supabase_auth_admin');
const hook=async email=>(await db.query('select public.club_before_user_created($1::jsonb) result',[JSON.stringify({user:{email}})])).rows[0].result;
assert.deepEqual(await hook('p1@test.invalid'),{});
assert.deepEqual(await hook(' P2@TEST.INVALID '),{});
assert.equal((await hook('outside@test.invalid')).error.http_code,403);
assert.equal((await hook('')).error.http_code,403);
assert.equal((await hook(null)).error.http_code,403);
await rejects(()=>db.query('select * from club_private.members'));
await as(2);
await rejects(()=>hook('p1@test.invalid'));
let s=await snapshot();assert.equal(s.players.filter(p=>p.ratings).length,1);assert.ok(s.players.find(p=>p.id===2).ratings);assert.equal(s.players.find(p=>p.id===1).goals,undefined);
await rejects(()=>db.query('select * from club_private.ballots'));await rejects(()=>act('ratings',{id:2,ratings:[90,90,90,90,90,90]}));
await rejects(()=>db.query('select public.club_claim_push(20)'));
await as(1);
await act('permission',{id:2,key:'seeAll',value:true});
await act('ratings',{id:2,ratings:[99,80,70,60,50,40]});
await rejects(()=>act('ratings',{id:2,ratings:[99,80,70,null,50,40]}));
await rejects(()=>act('match',{season:2026,date:'2026-10-08',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[1,7,8,9,10]}));
let m=await act('match',{season:2026,date:'2026-10-08',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[6,7,8,9,10]});
s=await snapshot();assert.equal(s.matches.length,1);assert.equal(s.notifications.length,1);
const result={};for(let i=1;i<=10;i++)result[i]={goals:i===1?2:0,own:i===6?1:0,present:true};
await act('result',{id:m.id,result});await act('result',{id:m.id,result});
s=await snapshot();assert.equal(s.players.find(p=>p.id===1).goals,2);assert.equal(s.players.find(p=>p.id===1).apps,1);assert.deepEqual(s.matches[0].score,[3,0]);
result[1].goals=1;await act('result',{id:m.id,result});s=await snapshot();assert.equal(s.players.find(p=>p.id===1).goals,1);assert.equal(s.players.find(p=>p.id===1).apps,1);
result[1].present=false;await rejects(()=>act('result',{id:m.id,result}));assert.equal((await snapshot()).players.find(p=>p.id===1).goals,1);
await act('round_open',{season:2026,award:'pollone'});let r=(await snapshot()).rounds[0];assert.equal(r.candidates.length,12);
await act('vote',{round:r.id,candidate:1});await rejects(()=>act('vote',{round:r.id,candidate:2}));
s=await snapshot();assert.equal(s.rounds[0].count,1);assert.deepEqual(s.rounds[0].results,[]);assert.equal(s.rounds[0].voted,true);
await as(2);assert.equal((await snapshot()).players.filter(p=>p.ratings).length,12);await act('vote',{round:r.id,candidate:1});
await as(1);await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1,2]}));await act('round_close',{id:r.id});
s=await snapshot();assert.deepEqual(s.rounds[0].results,[{id:1,count:2}]);
await act('round_open',{season:2026,award:'pollone',candidates:[1,2]});let second=(await snapshot()).rounds[1];assert.equal(second.count,0);assert.equal(second.voted,false);
await as(12);await act('vote',{round:second.id,candidate:1});await rejects(()=>act('vote',{round:second.id,candidate:12}));
await as(1);await act('round_close',{id:second.id});await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1,3]}));
for(let turn=3;turn<=4;turn++){await act('round_open',{season:2026,award:'pollone',candidates:[1]});let x=(await snapshot()).rounds.at(-1);await act('vote',{round:x.id,candidate:1});await act('round_close',{id:x.id});}
await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1]}));let last=(await snapshot()).rounds.at(-1);await act('round_final',{id:last.id});assert.equal((await snapshot()).rounds.at(-1).status,'final');
await act('round_open',{season:2026,award:'bidone'});assert.equal((await snapshot()).rounds.find(x=>x.award==='bidone').turn,1);
await act('round_open',{season:2027,award:'pollone'});assert.equal((await snapshot(2027)).rounds[0].turn,1);assert.equal((await snapshot(2027)).players.find(p=>p.id===1).goals,0);
await rejects(()=>act('permission',{id:1,key:'admin',value:false}));await rejects(()=>act('invite',{id:1,email:'wrong@test.invalid'}));
// Guests participate without membership, retain statistics, and can later get an account.
let guest=await act('player',{name:'Guest Player',role:'Attaccante',occasional:true,email:''});
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).occasional,true);
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).email,null);
await rejects(()=>act('player',{name:'Invalid Guest',role:'Attaccante',occasional:true,email:'guest@test.invalid'}));
let gm=await act('match',{season:2026,date:'2026-10-15',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
let gr={};for(const pid of [1,2,3,4,guest.id,6,7,8,9,10])gr[pid]={goals:pid===guest.id?2:0,own:pid===guest.id?1:0,present:true};
await act('result',{id:gm.id,result:gr});
s=await snapshot();assert.equal(s.players.find(p=>p.id===guest.id).goals,2);assert.equal(s.players.find(p=>p.id===guest.id).own,1);assert.equal(s.players.find(p=>p.id===guest.id).apps,1);
await as(2);await rejects(()=>act('match_cancel',{id:m.id,reason:'Unauthorized'}));
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).goals,2);
await as(1);await act('match_cancel',{id:m.id,reason:'Errore nel calendario'});
s=await snapshot();assert.equal(s.matches.find(x=>x.id===m.id).cancelled,true);assert.equal(s.players.find(p=>p.id===1).goals,0);assert.equal(s.players.find(p=>p.id===1).apps,1);
assert.ok(s.matches.find(x=>x.id===m.id).result);assert.equal(s.players.find(p=>p.id===guest.id).goals,2);
await rejects(()=>act('match_cancel',{id:m.id}));await rejects(()=>act('result',{id:m.id,result}));
await rejects(()=>act('match_cancel',{id:gm.id,reason:'x'.repeat(201)}));
await act('match_cancel',{id:gm.id});s=await snapshot();assert.equal(s.players.find(p=>p.id===guest.id).goals,0);assert.equal(s.players.find(p=>p.id===guest.id).own,0);assert.equal(s.players.find(p=>p.id===guest.id).apps,0);
let scheduled=await act('match',{season:2026,date:'2026-10-22',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
await act('match_cancel',{id:scheduled.id,reason:'Pioggia'});s=await snapshot();assert.equal(s.players.find(p=>p.id===1).apps,0);assert.equal(s.notifications.filter(n=>n.text.startsWith('Partita annullata')).length,3);
await as(1,'supabase_auth_admin');assert.equal((await hook('guest@test.invalid')).error.http_code,403);
await as(1);await act('invite',{id:guest.id,email:'guest@test.invalid'});assert.equal((await snapshot()).players.find(p=>p.id===guest.id).occasional,false);
await as(1,'supabase_auth_admin');assert.deepEqual(await hook('guest@test.invalid'),{});
await as(1,'service_role');let jobs=(await db.query('select public.club_claim_push(20) x')).rows[0].x;assert.equal(jobs.length,20);assert.ok(jobs.every(j=>j.body.startsWith('Partita annullata')));await db.query('select public.club_ack_push($1,$2,true)',[jobs[0].id,jobs[0].claim]);
await as(2);await rejects(()=>act('player_delete',{id:guest.id}));
await as(1);await rejects(()=>act('player_delete',{id:1}));
let pending=await act('match',{season:2026,date:'2026-10-29',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
await rejects(()=>act('player_delete',{id:guest.id}));await act('match_cancel',{id:pending.id});
let previous=await snapshot();await act('player_delete',{id:guest.id});s=await snapshot();assert.ok(!s.players.find(p=>p.id===guest.id));assert.equal(s.matches.length,previous.matches.length);assert.deepEqual(s.matches.map(m=>m.score),previous.matches.map(m=>m.score));
await as(1,'supabase_auth_admin');assert.equal((await hook('guest@test.invalid')).error.http_code,403);
await as(1);await rejects(()=>act('player_delete',{id:guest.id}));
let historic=await act('match',{season:2026,date:'2026-11-05',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[6,7,8,9,10]});
let historicResult={};for(let i=1;i<=10;i++)historicResult[i]={goals:i===2?3:0,own:0,present:true};await act('result',{id:historic.id,result:historicResult});
let beforeDelete=await snapshot();await act('player_delete',{id:2});s=await snapshot();assert.ok(!s.players.find(p=>p.id===2));assert.deepEqual(s.matches.find(m=>m.id===historic.id).score,[3,0]);assert.equal(s.players.find(p=>p.id===1).apps,beforeDelete.players.find(p=>p.id===1).apps);
assert.ok(s.rounds.every(r=>!r.candidates.includes(2)));assert.equal(s.rounds.find(r=>r.award==='pollone'&&r.turn===1).count,1);
await as(2);await rejects(()=>snapshot());await as(1,'supabase_auth_admin');assert.equal((await hook('p2@test.invalid')).error.http_code,403);

await db.exec('reset role');await db.query(`select set_config('request.test_uid','00000000-0000-0000-0000-000000000099',false)`);await db.exec('set role authenticated');await rejects(()=>snapshot());
await db.exec('reset role;set role anon');await rejects(()=>hook('p1@test.invalid'));let health=(await db.query('select public.club_health() x')).rows[0].x;assert.equal(health.ok,true);await rejects(()=>snapshot());
// Upgrade an existing database, then verify non-calendar seasons and archived writes.
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_custom_seasons.sql',import.meta.url),'utf8'));
await as(1);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_edit_matches.sql',import.meta.url),'utf8'));await as(1);
const editable=await act('match',{season:2026,date:'2026-11-12',time:'21:00',field:'Old field',a:[1,3,4,5,6],b:[7,8,9,10,11]});
const editData={id:editable.id,date:'2026-11-19',time:'20:30',field:'Oratorio Don Bosco Arena',a:[1,3,4,5,6],b:[7,8,9,10,12]};
await as(3);await rejects(()=>act('match_edit',editData));await as(1);
await rejects(()=>act('match_edit',{...editData,b:[1,8,9,10,12]}));
await act('match_edit',editData);let updated=(await snapshot()).matches.find(m=>m.id===editable.id);assert.equal(updated.date,editData.date);assert.equal(updated.time,editData.time);assert.deepEqual(updated.b,editData.b);assert.equal(updated.field,editData.field);
await as(11);let revoked=await snapshot();assert.ok(revoked.notifications.some(n=>n.matchId===editable.id&&n.text.startsWith('Convocazione revocata')));await as(1);
const editResult=Object.fromEntries([...editData.a,...editData.b].map(id=>[id,{goals:id===12?4:id===1?2:0,own:0,present:true}]));await act('result',{id:editable.id,result:editResult});
const beforeEdit=await snapshot();await act('match_edit',{...editData,b:[7,8,9,10,11]});
updated=(await snapshot()).matches.find(m=>m.id===editable.id);assert.deepEqual(updated.score,[2,0]);assert.deepEqual(updated.result['11'],{goals:0,own:0,present:false});assert.ok(!updated.result['12']);
assert.equal((await snapshot()).players.find(p=>p.id===12).goals,beforeEdit.players.find(p=>p.id===12).goals-4);
await act('match_edit',{...editData,b:[7,8,9,10,11]});assert.deepEqual((await snapshot()).matches.find(m=>m.id===editable.id).score,[2,0]);
await act('match_cancel',{id:editable.id});await rejects(()=>act('match_edit',editData));
let active=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
assert.equal(active.activeSeason,2026);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_current_season_label.sql',import.meta.url),'utf8'));await as(3);
await rejects(()=>act('round_open',{season:2026,award:'pollone'}));await as(1);
assert.equal((await snapshot()).seasonInfo.name,'2025/2026');
await as(3);await rejects(()=>act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'}));await as(1);
await act('match',{season:2026,date:'2026-12-03',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});
await rejects(()=>act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'}));
await db.exec('reset role');await db.exec("update club_private.matches set cancelled_at=now() where result is null and cancelled_at is null");await as(1);
const next=await act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'});
active=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
assert.equal(active.season,next.id);assert.equal(active.seasonInfo.name,'2026/2027');assert.ok(active.players.every(p=>p.goals===0&&p.apps===0));
await rejects(()=>act('season_start',{previous:2026,name:'duplicate',started_on:'2026-09-01'}));
await rejects(()=>act('result',{id:historic.id,result:historicResult}));
await rejects(()=>act('match_edit',{...editData,id:historic.id}));
await rejects(()=>act('round_open',{season:2026,award:'bidone'}));
const crossYear=await act('match',{season:next.id,date:'2026-12-10',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});
assert.ok(crossYear.id);
const january=await act('match',{season:next.id,date:'2027-01-14',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});assert.ok(january.id);
assert.ok((await snapshot()).seasonInfo.closed_at);
// Members without statistics access see archived winners only.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_closed_award_winners.sql',import.meta.url),'utf8'));
await as(1);const archivedAdmin=await snapshot();const expectedWinners={};for(const key of ['goals','own','apps']){const max=Math.max(0,...archivedAdmin.players.map(p=>p[key]));if(max)expectedWinners[key]=archivedAdmin.players.filter(p=>p[key]===max).map(p=>({id:p.id,name:p.name}))}
await as(3);const archivedMember=await snapshot();assert.deepEqual(archivedMember.closedAwards,expectedWinners);assert.equal(archivedMember.players.find(p=>p.id===1).goals,undefined);assert.equal(archivedMember.players.find(p=>p.id===1).ratings,undefined);
assert.ok(Object.values(archivedMember.closedAwards).flat().every(w=>Object.keys(w).sort().join(',')==='id,name'));
assert.deepEqual((await db.query('select public.club_snapshot(null) x')).rows[0].x.closedAwards,{});
await db.exec('reset role;set role anon');await rejects(()=>snapshot());

// Push configuration is readable only by members; scheduler setup is transactional and repeatable.
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_push_config.sql',import.meta.url),'utf8'));
await as(3);assert.equal((await db.query('select public.club_push_config() x')).rows[0].x.publicKey,null);
await db.exec('reset role;set role anon');await rejects(()=>db.query('select public.club_push_config()'));
await db.exec('reset role');
await db.exec(`create schema vault;create schema cron;create schema net;
create table vault.secrets(id uuid default gen_random_uuid(),name text unique,decrypted_secret text);
create view vault.decrypted_secrets as select * from vault.secrets;
create function vault.create_secret(v text,n text) returns uuid language plpgsql as $$declare i uuid;begin insert into vault.secrets(name,decrypted_secret)values(n,v)returning id into i;return i;end$$;
create function vault.update_secret(i uuid,v text,n text) returns void language sql as $$update vault.secrets set name=n,decrypted_secret=v where id=i$$;
create table cron.jobs(name text primary key,schedule text,command text);
create function cron.schedule(n text,s text,c text) returns bigint language plpgsql as $$begin insert into cron.jobs values(n,s,c)on conflict(name)do update set schedule=s,command=c;return 1;end$$;`);
let pushSql=await readFile(new URL('../web/push-setup.sql',import.meta.url),'utf8');
pushSql=pushSql.replace(/^create extension.*;$/gm,'').replaceAll('__PUBLIC_KEY__','B'.repeat(87)).replaceAll('__PROJECT_URL__','https://test.supabase.co').replaceAll('__PUBLISHABLE_KEY__','public-key').replaceAll('__CRON_SECRET__','test-cron-secret');
await db.exec(pushSql);await db.exec(pushSql);
assert.equal((await db.query('select count(*) n from cron.jobs')).rows[0].n,1);
assert.equal((await db.query('select count(*) n from vault.secrets')).rows[0].n,3);
await as(3);assert.equal((await db.query('select public.club_push_config() x')).rows[0].x.publicKey,'B'.repeat(87));
await rejects(()=>db.query('select * from club_private.push_config'));
await db.exec('reset role');await rejects(()=>db.exec(pushSql.replaceAll('B'.repeat(87),'C'.repeat(87))));await db.exec('rollback');
// Install permanent awards and additional statistics on the existing production-style schema.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_hall_and_match_stats.sql',import.meta.url),'utf8'));await as(1);
const frozenBefore=(await snapshot()).closedAwards;assert.equal(Object.keys(frozenBefore).length,5);
assert.ok((await snapshot()).hallOfFame.some(s=>s.season===2026));
const teamA=[1,3,4,5,6],teamB=[7,8,9,10,11];
const makeResult=(aGoals,bGoals,absent=[])=>Object.fromEntries([...teamA,...teamB].map(id=>[id,{goals:id===1?aGoals:id===8?bGoals:0,own:0,present:!absent.includes(id)}]));
let winResult=makeResult(2,1,[3]);winResult[7].own=1;await act('result',{id:crossYear.id,result:winResult});
await act('result',{id:january.id,result:makeResult(1,1)});
const lossMatch=await act('match',{season:next.id,date:'2027-02-01',time:'21:00',field:'Oratorio Don Bosco Arena',a:teamA,b:teamB});
await act('result',{id:lossMatch.id,result:makeResult(0,2)});
let extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
const one=extended.players.find(p=>p.id===1);assert.deepEqual([one.apps,one.wins,one.draws,one.losses,one.winRate,one.goalAverage],[3,1,1,1,33.33,1]);
const absent=extended.players.find(p=>p.id===3);assert.deepEqual([absent.apps,absent.wins,absent.draws,absent.losses],[2,0,1,1]);
const zero=extended.players.find(p=>p.id===12);assert.deepEqual([zero.apps,zero.wins,zero.draws,zero.losses,zero.winRate,zero.goalAverage],[0,0,0,0,0,0]);
await act('result',{id:lossMatch.id,result:makeResult(2,0)});await act('result',{id:lossMatch.id,result:makeResult(2,0)});
assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===1).wins,2);
await act('match_cancel',{id:lossMatch.id});extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.deepEqual([extended.players.find(p=>p.id===1).apps,extended.players.find(p=>p.id===1).wins],[2,1]);
await as(3);extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.ok('wins' in extended.players.find(p=>p.id===3));for(const key of ['wins','draws','losses','winRate','goalAverage'])assert.equal(extended.players.find(p=>p.id===1)[key],undefined);await as(1);
if(!(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.some(r=>r.award==='pollone'))await act('round_open',{season:next.id,award:'pollone'});let finalPollone=(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.find(r=>r.award==='pollone');
await act('vote',{round:finalPollone.id,candidate:12});await act('round_close',{id:finalPollone.id});await act('round_final',{id:finalPollone.id});
await act('round_open',{season:next.id,award:'bidone'});let finalBidone=(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.find(r=>r.award==='bidone');await act('vote',{round:finalBidone.id,candidate:12});
await as(3);await act('vote',{round:finalBidone.id,candidate:11});await as(1);await act('round_close',{id:finalBidone.id});await act('round_final',{id:finalBidone.id});
await act('season_start',{previous:next.id,name:'2027/2028',started_on:'2027-09-01'});
const archive=(await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x;
assert.deepEqual(archive.closedAwards.pollone,[{id:12,name:'Player 12'}]);assert.equal(archive.closedAwards.bidone.length,2);
const frozen=structuredClone(archive.closedAwards);await act('player_delete',{id:12});await act('player_delete',{id:11});
const stillFrozen=(await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x;assert.deepEqual(stillFrozen.closedAwards,frozen);assert.deepEqual(stillFrozen.hallOfFame.find(s=>s.season===next.id).awards,frozen);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_hall_and_match_stats.sql',import.meta.url),'utf8'));await as(3);
assert.deepEqual((await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x.closedAwards,frozen);
await rejects(()=>db.query('select * from club_private.season_awards'));await rejects(()=>db.query('select club_private.capture_awards($1)',[next.id]));
await db.exec('reset role;set role anon');await rejects(()=>snapshot());
// Hardening: anonymous health has no elevated rights; automatic RLS trigger survives ACL changes.
await db.exec('reset role');
await db.exec(`create function public.rls_auto_enable() returns event_trigger language plpgsql security definer set search_path='' as $$declare cmd record;begin
for cmd in select * from pg_event_trigger_ddl_commands() where command_tag='CREATE TABLE' and schema_name='public' loop
 execute format('alter table %s enable row level security',cmd.object_identity);
end loop;end$$;
create event trigger test_auto_rls on ddl_command_end when tag in ('CREATE TABLE') execute function public.rls_auto_enable();
grant execute on function public.rls_auto_enable() to anon,authenticated;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
assert.equal((await db.query("select prosecdef from pg_proc where oid='public.club_health()'::regprocedure")).rows[0].prosecdef,false);
for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'public.rls_auto_enable()','EXECUTE') allowed",[role])).rows[0].allowed,false);
await db.exec('create table public.test_automatic_rls(id integer)');assert.equal((await db.query("select relrowsecurity from pg_class where oid='public.test_automatic_rls'::regclass")).rows[0].relrowsecurity,true);
await db.exec('set role anon');assert.deepEqual((await db.query('select public.club_health() x')).rows[0].x,{ok:true});await rejects(()=>snapshot());
await as(3);assert.ok((await snapshot()).user===3);await rejects(()=>act('player',{name:'Unauthorized',role:'Regista'}));
await db.exec('reset role');await db.exec('drop event trigger test_auto_rls;drop table public.test_automatic_rls;drop function public.rls_auto_enable()');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
await db.close();console.log('PASS database: private tables, membership, permissions, own statistics, duplicate votes, self votes, 4 rounds, independent awards, seasons, result corrections, notifications, service-only push queue');
