import { PGlite } from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated;create role service_role; create role supabase_auth_admin;
create schema auth;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.test_uid',true),'')::uuid$$;`);
await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_cancel_matches_and_guests.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_delete_player.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_invite_only_signup.sql',import.meta.url),'utf8'));
for(let i=1;i<=12;i++){
 await db.query(`insert into club_private.players(id,name,role) values($1,$2,'Regista')`,[i,'Player '+i]);
 await db.query(`insert into club_private.members(player_id,email,is_admin,see_all) values($1,$2,$3,false)`,[i,`p${i}@test.invalid`,i===1]);
 await db.query(`insert into auth.users values($1,$2,now())`,[`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`,`p${i}@test.invalid`]);
}
await db.exec(`select setval(pg_get_serial_sequence('club_private.players','id'),12,true)`);
async function as(i,role='authenticated'){
 await db.exec('reset role');await db.query(`select set_config('request.test_uid',$1,false)`,[`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`]);await db.exec(`set role ${role}`);
}
const act=async (action,data)=> (await db.query('select public.club_action($1,$2::jsonb) result',[action,JSON.stringify(data)])).rows[0].result;
const snapshot=async (season=2026)=>(await db.query('select public.club_snapshot($1) result',[season])).rows[0].result;
async function rejects(fn){await assert.rejects(fn)}
await as(1,'supabase_auth_admin');
const hook=async email=>(await db.query('select public.club_before_user_created($1::jsonb) result',[JSON.stringify({user:{email}})])).rows[0].result;
assert.deepEqual(await hook('p1@test.invalid'),{});
assert.deepEqual(await hook(' P2@TEST.INVALID '),{});
assert.equal((await hook('outside@test.invalid')).error.http_code,403);
assert.equal((await hook('')).error.http_code,403);
assert.equal((await hook(null)).error.http_code,403);
await rejects(()=>db.query('select * from club_private.members'));
await as(2);
await rejects(()=>hook('p1@test.invalid'));
let s=await snapshot();assert.equal(s.players.filter(p=>p.ratings).length,1);assert.ok(s.players.find(p=>p.id===2).ratings);assert.equal(s.players.find(p=>p.id===1).goals,undefined);
await rejects(()=>db.query('select * from club_private.ballots'));await rejects(()=>act('ratings',{id:2,ratings:[90,90,90,90,90,90]}));
await rejects(()=>db.query('select public.club_claim_push(20)'));
await as(1);
await act('permission',{id:2,key:'seeAll',value:true});
await act('ratings',{id:2,ratings:[99,80,70,60,50,40]});
await rejects(()=>act('ratings',{id:2,ratings:[99,80,70,null,50,40]}));
await rejects(()=>act('match',{season:2026,date:'2026-10-08',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[1,7,8,9,10]}));
let m=await act('match',{season:2026,date:'2026-10-08',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[6,7,8,9,10]});
s=await snapshot();assert.equal(s.matches.length,1);assert.equal(s.notifications.length,1);
const result={};for(let i=1;i<=10;i++)result[i]={goals:i===1?2:0,own:i===6?1:0,present:true};
await act('result',{id:m.id,result});await act('result',{id:m.id,result});
s=await snapshot();assert.equal(s.players.find(p=>p.id===1).goals,2);assert.equal(s.players.find(p=>p.id===1).apps,1);assert.deepEqual(s.matches[0].score,[3,0]);
result[1].goals=1;await act('result',{id:m.id,result});s=await snapshot();assert.equal(s.players.find(p=>p.id===1).goals,1);assert.equal(s.players.find(p=>p.id===1).apps,1);
result[1].present=false;await rejects(()=>act('result',{id:m.id,result}));assert.equal((await snapshot()).players.find(p=>p.id===1).goals,1);
await act('round_open',{season:2026,award:'pollone'});let r=(await snapshot()).rounds[0];assert.equal(r.candidates.length,12);
await act('vote',{round:r.id,candidate:1});await rejects(()=>act('vote',{round:r.id,candidate:2}));
s=await snapshot();assert.equal(s.rounds[0].count,1);assert.deepEqual(s.rounds[0].results,[]);assert.equal(s.rounds[0].voted,true);
await as(2);assert.equal((await snapshot()).players.filter(p=>p.ratings).length,12);await act('vote',{round:r.id,candidate:1});
await as(1);await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1,2]}));await act('round_close',{id:r.id});
s=await snapshot();assert.deepEqual(s.rounds[0].results,[{id:1,count:2}]);
await act('round_open',{season:2026,award:'pollone',candidates:[1,2]});let second=(await snapshot()).rounds[1];assert.equal(second.count,0);assert.equal(second.voted,false);
await as(12);await act('vote',{round:second.id,candidate:1});await rejects(()=>act('vote',{round:second.id,candidate:12}));
await as(1);await act('round_close',{id:second.id});await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1,3]}));
for(let turn=3;turn<=4;turn++){await act('round_open',{season:2026,award:'pollone',candidates:[1]});let x=(await snapshot()).rounds.at(-1);await act('vote',{round:x.id,candidate:1});await act('round_close',{id:x.id});}
await rejects(()=>act('round_open',{season:2026,award:'pollone',candidates:[1]}));let last=(await snapshot()).rounds.at(-1);await act('round_final',{id:last.id});assert.equal((await snapshot()).rounds.at(-1).status,'final');
await act('round_open',{season:2026,award:'bidone'});assert.equal((await snapshot()).rounds.find(x=>x.award==='bidone').turn,1);
await act('round_open',{season:2027,award:'pollone'});assert.equal((await snapshot(2027)).rounds[0].turn,1);assert.equal((await snapshot(2027)).players.find(p=>p.id===1).goals,0);
await rejects(()=>act('permission',{id:1,key:'admin',value:false}));await rejects(()=>act('invite',{id:1,email:'wrong@test.invalid'}));
// Guests participate without membership, retain statistics, and can later get an account.
let guest=await act('player',{name:'Guest Player',role:'Attaccante',occasional:true,email:''});
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).occasional,true);
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).email,null);
await rejects(()=>act('player',{name:'Invalid Guest',role:'Attaccante',occasional:true,email:'guest@test.invalid'}));
let gm=await act('match',{season:2026,date:'2026-10-15',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
let gr={};for(const pid of [1,2,3,4,guest.id,6,7,8,9,10])gr[pid]={goals:pid===guest.id?2:0,own:pid===guest.id?1:0,present:true};
await act('result',{id:gm.id,result:gr});
s=await snapshot();assert.equal(s.players.find(p=>p.id===guest.id).goals,2);assert.equal(s.players.find(p=>p.id===guest.id).own,1);assert.equal(s.players.find(p=>p.id===guest.id).apps,1);
await as(2);await rejects(()=>act('match_cancel',{id:m.id,reason:'Unauthorized'}));
assert.equal((await snapshot()).players.find(p=>p.id===guest.id).goals,2);
await as(1);await act('match_cancel',{id:m.id,reason:'Errore nel calendario'});
s=await snapshot();assert.equal(s.matches.find(x=>x.id===m.id).cancelled,true);assert.equal(s.players.find(p=>p.id===1).goals,0);assert.equal(s.players.find(p=>p.id===1).apps,1);
assert.ok(s.matches.find(x=>x.id===m.id).result);assert.equal(s.players.find(p=>p.id===guest.id).goals,2);
await rejects(()=>act('match_cancel',{id:m.id}));await rejects(()=>act('result',{id:m.id,result}));
await rejects(()=>act('match_cancel',{id:gm.id,reason:'x'.repeat(201)}));
await act('match_cancel',{id:gm.id});s=await snapshot();assert.equal(s.players.find(p=>p.id===guest.id).goals,0);assert.equal(s.players.find(p=>p.id===guest.id).own,0);assert.equal(s.players.find(p=>p.id===guest.id).apps,0);
let scheduled=await act('match',{season:2026,date:'2026-10-22',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
await act('match_cancel',{id:scheduled.id,reason:'Pioggia'});s=await snapshot();assert.equal(s.players.find(p=>p.id===1).apps,0);assert.equal(s.notifications.filter(n=>n.text.startsWith('Partita annullata')).length,3);
await as(1,'supabase_auth_admin');assert.equal((await hook('guest@test.invalid')).error.http_code,403);
await as(1);await act('invite',{id:guest.id,email:'guest@test.invalid'});assert.equal((await snapshot()).players.find(p=>p.id===guest.id).occasional,false);
await as(1,'supabase_auth_admin');assert.deepEqual(await hook('guest@test.invalid'),{});
await as(1,'service_role');let jobs=(await db.query('select public.club_claim_push(20) x')).rows[0].x;assert.equal(jobs.length,20);assert.ok(jobs.every(j=>j.body.startsWith('Partita annullata')));await db.query('select public.club_ack_push($1,$2,true)',[jobs[0].id,jobs[0].claim]);
await as(2);await rejects(()=>act('player_delete',{id:guest.id}));
await as(1);await rejects(()=>act('player_delete',{id:1}));
let pending=await act('match',{season:2026,date:'2026-10-29',time:'21:00',field:'Jumbo',a:[1,2,3,4,guest.id],b:[6,7,8,9,10]});
await rejects(()=>act('player_delete',{id:guest.id}));await act('match_cancel',{id:pending.id});
let previous=await snapshot();await act('player_delete',{id:guest.id});s=await snapshot();assert.ok(!s.players.find(p=>p.id===guest.id));assert.equal(s.matches.length,previous.matches.length);assert.deepEqual(s.matches.map(m=>m.score),previous.matches.map(m=>m.score));
await as(1,'supabase_auth_admin');assert.equal((await hook('guest@test.invalid')).error.http_code,403);
await as(1);await rejects(()=>act('player_delete',{id:guest.id}));
let historic=await act('match',{season:2026,date:'2026-11-05',time:'21:00',field:'Jumbo',a:[1,2,3,4,5],b:[6,7,8,9,10]});
let historicResult={};for(let i=1;i<=10;i++)historicResult[i]={goals:i===2?3:0,own:0,present:true};await act('result',{id:historic.id,result:historicResult});
let beforeDelete=await snapshot();await act('player_delete',{id:2});s=await snapshot();assert.ok(!s.players.find(p=>p.id===2));assert.deepEqual(s.matches.find(m=>m.id===historic.id).score,[3,0]);assert.equal(s.players.find(p=>p.id===1).apps,beforeDelete.players.find(p=>p.id===1).apps);
assert.ok(s.rounds.every(r=>!r.candidates.includes(2)));assert.equal(s.rounds.find(r=>r.award==='pollone'&&r.turn===1).count,1);
await as(2);await rejects(()=>snapshot());await as(1,'supabase_auth_admin');assert.equal((await hook('p2@test.invalid')).error.http_code,403);

await db.exec('reset role');await db.query(`select set_config('request.test_uid','00000000-0000-0000-0000-000000000099',false)`);await db.exec('set role authenticated');await rejects(()=>snapshot());
await db.exec('reset role;set role anon');await rejects(()=>hook('p1@test.invalid'));let health=(await db.query('select public.club_health() x')).rows[0].x;assert.equal(health.ok,true);await rejects(()=>snapshot());
// Upgrade an existing database, then verify non-calendar seasons and archived writes.
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_custom_seasons.sql',import.meta.url),'utf8'));
await as(1);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_edit_matches.sql',import.meta.url),'utf8'));await as(1);
const editable=await act('match',{season:2026,date:'2026-11-12',time:'21:00',field:'Old field',a:[1,3,4,5,6],b:[7,8,9,10,11]});
const editData={id:editable.id,date:'2026-11-19',time:'20:30',field:'Oratorio Don Bosco Arena',a:[1,3,4,5,6],b:[7,8,9,10,12]};
await as(3);await rejects(()=>act('match_edit',editData));await as(1);
await rejects(()=>act('match_edit',{...editData,b:[1,8,9,10,12]}));
await act('match_edit',editData);let updated=(await snapshot()).matches.find(m=>m.id===editable.id);assert.equal(updated.date,editData.date);assert.equal(updated.time,editData.time);assert.deepEqual(updated.b,editData.b);assert.equal(updated.field,editData.field);
await as(11);let revoked=await snapshot();assert.ok(revoked.notifications.some(n=>n.matchId===editable.id&&n.text.startsWith('Convocazione revocata')));await as(1);
const editResult=Object.fromEntries([...editData.a,...editData.b].map(id=>[id,{goals:id===12?4:id===1?2:0,own:0,present:true}]));await act('result',{id:editable.id,result:editResult});
const beforeEdit=await snapshot();await act('match_edit',{...editData,b:[7,8,9,10,11]});
updated=(await snapshot()).matches.find(m=>m.id===editable.id);assert.deepEqual(updated.score,[2,0]);assert.deepEqual(updated.result['11'],{goals:0,own:0,present:false});assert.ok(!updated.result['12']);
assert.equal((await snapshot()).players.find(p=>p.id===12).goals,beforeEdit.players.find(p=>p.id===12).goals-4);
await act('match_edit',{...editData,b:[7,8,9,10,11]});assert.deepEqual((await snapshot()).matches.find(m=>m.id===editable.id).score,[2,0]);
await act('match_cancel',{id:editable.id});await rejects(()=>act('match_edit',editData));
let active=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
assert.equal(active.activeSeason,2026);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_current_season_label.sql',import.meta.url),'utf8'));await as(3);
await rejects(()=>act('round_open',{season:2026,award:'pollone'}));await as(1);
assert.equal((await snapshot()).seasonInfo.name,'2025/2026');
await as(3);await rejects(()=>act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'}));await as(1);
await act('match',{season:2026,date:'2026-12-03',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});
await rejects(()=>act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'}));
await db.exec('reset role');await db.exec("update club_private.matches set cancelled_at=now() where result is null and cancelled_at is null");await as(1);
const next=await act('season_start',{previous:2026,name:'2026/2027',started_on:'2026-09-01'});
active=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
assert.equal(active.season,next.id);assert.equal(active.seasonInfo.name,'2026/2027');assert.ok(active.players.every(p=>p.goals===0&&p.apps===0));
await rejects(()=>act('season_start',{previous:2026,name:'duplicate',started_on:'2026-09-01'}));
await rejects(()=>act('result',{id:historic.id,result:historicResult}));
await rejects(()=>act('match_edit',{...editData,id:historic.id}));
await rejects(()=>act('round_open',{season:2026,award:'bidone'}));
const crossYear=await act('match',{season:next.id,date:'2026-12-10',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});
assert.ok(crossYear.id);
const january=await act('match',{season:next.id,date:'2027-01-14',time:'21:00',field:'Jumbo',a:[1,3,4,5,6],b:[7,8,9,10,11]});assert.ok(january.id);
assert.ok((await snapshot()).seasonInfo.closed_at);
// Members without statistics access see archived winners only.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_closed_award_winners.sql',import.meta.url),'utf8'));
await as(1);const archivedAdmin=await snapshot();const expectedWinners={};for(const key of ['goals','own','apps']){const max=Math.max(0,...archivedAdmin.players.map(p=>p[key]));if(max)expectedWinners[key]=archivedAdmin.players.filter(p=>p[key]===max).map(p=>({id:p.id,name:p.name}))}
await as(3);const archivedMember=await snapshot();assert.deepEqual(archivedMember.closedAwards,expectedWinners);assert.equal(archivedMember.players.find(p=>p.id===1).goals,undefined);assert.equal(archivedMember.players.find(p=>p.id===1).ratings,undefined);
assert.ok(Object.values(archivedMember.closedAwards).flat().every(w=>Object.keys(w).sort().join(',')==='id,name'));
assert.deepEqual((await db.query('select public.club_snapshot(null) x')).rows[0].x.closedAwards,{});
await db.exec('reset role;set role anon');await rejects(()=>snapshot());

// Push configuration is readable only by members; scheduler setup is transactional and repeatable.
await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_push_config.sql',import.meta.url),'utf8'));
await as(3);assert.equal((await db.query('select public.club_push_config() x')).rows[0].x.publicKey,null);
await db.exec('reset role;set role anon');await rejects(()=>db.query('select public.club_push_config()'));
await db.exec('reset role');
await db.exec(`create schema vault;create schema cron;create schema net;
create table vault.secrets(id uuid default gen_random_uuid(),name text unique,decrypted_secret text);
create view vault.decrypted_secrets as select * from vault.secrets;
create function vault.create_secret(v text,n text) returns uuid language plpgsql as $$declare i uuid;begin insert into vault.secrets(name,decrypted_secret)values(n,v)returning id into i;return i;end$$;
create function vault.update_secret(i uuid,v text,n text) returns void language sql as $$update vault.secrets set name=n,decrypted_secret=v where id=i$$;
create table cron.jobs(name text primary key,schedule text,command text);
create function cron.schedule(n text,s text,c text) returns bigint language plpgsql as $$begin insert into cron.jobs values(n,s,c)on conflict(name)do update set schedule=s,command=c;return 1;end$$;`);
let pushSql=await readFile(new URL('../web/push-setup.sql',import.meta.url),'utf8');
pushSql=pushSql.replace(/^create extension.*;$/gm,'').replaceAll('__PUBLIC_KEY__','B'.repeat(87)).replaceAll('__PROJECT_URL__','https://test.supabase.co').replaceAll('__PUBLISHABLE_KEY__','public-key').replaceAll('__CRON_SECRET__','test-cron-secret');
await db.exec(pushSql);await db.exec(pushSql);
assert.equal((await db.query('select count(*) n from cron.jobs')).rows[0].n,1);
assert.equal((await db.query('select count(*) n from vault.secrets')).rows[0].n,3);
await as(3);assert.equal((await db.query('select public.club_push_config() x')).rows[0].x.publicKey,'B'.repeat(87));
await rejects(()=>db.query('select * from club_private.push_config'));
await db.exec('reset role');await rejects(()=>db.exec(pushSql.replaceAll('B'.repeat(87),'C'.repeat(87))));await db.exec('rollback');
// Install permanent awards and additional statistics on the existing production-style schema.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_hall_and_match_stats.sql',import.meta.url),'utf8'));await as(1);
const frozenBefore=(await snapshot()).closedAwards;assert.equal(Object.keys(frozenBefore).length,5);
assert.ok((await snapshot()).hallOfFame.some(s=>s.season===2026));
const teamA=[1,3,4,5,6],teamB=[7,8,9,10,11];
const makeResult=(aGoals,bGoals,absent=[])=>Object.fromEntries([...teamA,...teamB].map(id=>[id,{goals:id===1?aGoals:id===8?bGoals:0,own:0,present:!absent.includes(id)}]));
let winResult=makeResult(2,1,[3]);winResult[7].own=1;await act('result',{id:crossYear.id,result:winResult});
await act('result',{id:january.id,result:makeResult(1,1)});
const lossMatch=await act('match',{season:next.id,date:'2027-02-01',time:'21:00',field:'Oratorio Don Bosco Arena',a:teamA,b:teamB});
await act('result',{id:lossMatch.id,result:makeResult(0,2)});
let extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
const one=extended.players.find(p=>p.id===1);assert.deepEqual([one.apps,one.wins,one.draws,one.losses,one.winRate,one.goalAverage],[3,1,1,1,33.33,1]);
const absent=extended.players.find(p=>p.id===3);assert.deepEqual([absent.apps,absent.wins,absent.draws,absent.losses],[2,0,1,1]);
const zero=extended.players.find(p=>p.id===12);assert.deepEqual([zero.apps,zero.wins,zero.draws,zero.losses,zero.winRate,zero.goalAverage],[0,0,0,0,0,0]);
await act('result',{id:lossMatch.id,result:makeResult(2,0)});await act('result',{id:lossMatch.id,result:makeResult(2,0)});
assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===1).wins,2);
await act('match_cancel',{id:lossMatch.id});extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.deepEqual([extended.players.find(p=>p.id===1).apps,extended.players.find(p=>p.id===1).wins],[2,1]);
await as(3);extended=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.ok('wins' in extended.players.find(p=>p.id===3));for(const key of ['wins','draws','losses','winRate','goalAverage'])assert.equal(extended.players.find(p=>p.id===1)[key],undefined);await as(1);
if(!(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.some(r=>r.award==='pollone'))await act('round_open',{season:next.id,award:'pollone'});let finalPollone=(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.find(r=>r.award==='pollone');
await act('vote',{round:finalPollone.id,candidate:12});await act('round_close',{id:finalPollone.id});await act('round_final',{id:finalPollone.id});
await act('round_open',{season:next.id,award:'bidone'});let finalBidone=(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.find(r=>r.award==='bidone');await act('vote',{round:finalBidone.id,candidate:12});
await as(3);await act('vote',{round:finalBidone.id,candidate:11});await as(1);await act('round_close',{id:finalBidone.id});await act('round_final',{id:finalBidone.id});
await act('season_start',{previous:next.id,name:'2027/2028',started_on:'2027-09-01'});
const archive=(await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x;
assert.deepEqual(archive.closedAwards.pollone,[{id:12,name:'Player 12'}]);assert.equal(archive.closedAwards.bidone.length,2);
const frozen=structuredClone(archive.closedAwards);await act('player_delete',{id:12});await act('player_delete',{id:11});
const stillFrozen=(await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x;assert.deepEqual(stillFrozen.closedAwards,frozen);assert.deepEqual(stillFrozen.hallOfFame.find(s=>s.season===next.id).awards,frozen);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_hall_and_match_stats.sql',import.meta.url),'utf8'));await as(3);
assert.deepEqual((await db.query('select public.club_snapshot($1) x',[next.id])).rows[0].x.closedAwards,frozen);
await rejects(()=>db.query('select * from club_private.season_awards'));await rejects(()=>db.query('select club_private.capture_awards($1)',[next.id]));
await db.exec('reset role;set role anon');await rejects(()=>snapshot());
// Hardening: anonymous health has no elevated rights; automatic RLS trigger survives ACL changes.
await db.exec('reset role');
await db.exec(`create function public.rls_auto_enable() returns event_trigger language plpgsql security definer set search_path='' as $$declare cmd record;begin
for cmd in select * from pg_event_trigger_ddl_commands() where command_tag='CREATE TABLE' and schema_name='public' loop
 execute format('alter table %s enable row level security',cmd.object_identity);
end loop;end$$;
create event trigger test_auto_rls on ddl_command_end when tag in ('CREATE TABLE') execute function public.rls_auto_enable();
grant execute on function public.rls_auto_enable() to anon,authenticated;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
assert.equal((await db.query("select prosecdef from pg_proc where oid='public.club_health()'::regprocedure")).rows[0].prosecdef,false);
for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'public.rls_auto_enable()','EXECUTE') allowed",[role])).rows[0].allowed,false);
await db.exec('create table public.test_automatic_rls(id integer)');assert.equal((await db.query("select relrowsecurity from pg_class where oid='public.test_automatic_rls'::regclass")).rows[0].relrowsecurity,true);
await db.exec('set role anon');assert.deepEqual((await db.query('select public.club_health() x')).rows[0].x,{ok:true});await rejects(()=>snapshot());
await as(3);assert.ok((await snapshot()).user===3);await rejects(()=>act('player',{name:'Unauthorized',role:'Regista'}));
await db.exec('reset role');await db.exec('drop event trigger test_auto_rls;drop table public.test_automatic_rls;drop function public.rls_auto_enable()');
await db.exec(await readFile(new URL('../supabase/migrations/20261006_security_advisor_hardening.sql',import.meta.url),'utf8'));
// Automatic reminders: timezone, deadlines, exact-once queueing and admin settings.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_automatic_reminders.sql',import.meta.url),'utf8'));
await as(1);let reminderConfig=(await db.query('select public.club_snapshot(null) x')).rows[0].x.reminderSettings;assert.equal(reminderConfig.first_hours,8);assert.equal(reminderConfig.second_hours,1);
await as(4);assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.reminderSettings,null);await rejects(()=>act('reminder_settings',reminderConfig));await rejects(()=>db.query('select club_private.enqueue_reminders()'));await as(1);
await rejects(()=>act('reminder_settings',{...reminderConfig,first_hours:1,second_hours:8}));await rejects(()=>act('reminder_settings',{...reminderConfig,result_max_reminders:0}));
await act('reminder_settings',{...reminderConfig,first_hours:10,second_hours:2});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.reminderSettings.first_hours,10);await act('reminder_settings',reminderConfig);
const occasionalReminder=await act('player',{name:'Reminder guest',role:'Portiere',occasional:true,email:''});await act('permission',{id:3,key:'admin',value:true});
await db.exec('reset role');const reminderSeason=(await db.query('select id from club_private.seasons where closed_at is null')).rows[0].id;
const reminderA=[1,3,4,5,6],reminderB=[7,8,9,10,occasionalReminder.id];
const fixture=async(date,time='21:00',updated='2027-01-01T00:00:00Z')=>(await db.query(`insert into club_private.matches(season,match_date,match_time,field,team_a,team_b,updated_at) values($1,$2,$3,'Reminder Arena',$4,$5,$6) returning id`,[reminderSeason,date,time,JSON.stringify(reminderA),JSON.stringify(reminderB),updated])).rows[0].id;
const pump=async(time)=>(await db.query('select club_private.enqueue_reminders($1::timestamptz) n',[time])).rows[0].n;
const notes=async(match)=>(await db.query('select player_id,reminder_key,text from club_private.notifications where match_id=$1 and reminder_key is not null order by id',[match])).rows;
const winter=await fixture('2028-01-10');assert.equal(await pump('2028-01-10T11:59:59Z'),0);assert.equal(await pump('2028-01-10T12:00:00Z'),9);assert.equal(await pump('2028-01-10T12:05:00Z'),0);
assert.equal((await notes(winter)).length,9);assert.ok(!(await notes(winter)).some(n=>n.player_id===occasionalReminder.id));
assert.equal(await pump('2028-01-10T19:00:00Z'),9);assert.equal((await notes(winter)).length,18);
assert.equal(await pump('2028-01-10T21:59:59Z'),0);assert.equal(await pump('2028-01-10T22:00:00Z'),2);assert.deepEqual((await notes(winter)).filter(n=>n.reminder_key.startsWith('result:')).map(n=>n.player_id).sort(),[1,3]);assert.equal(await pump('2028-01-11T22:00:00Z'),0);
await db.query('update club_private.matches set cancelled_at=now() where id=$1',[winter]);
const summer=await fixture('2028-07-10');assert.equal(await pump('2028-07-10T10:59:59Z'),0);assert.equal(await pump('2028-07-10T11:00:00Z'),9);await db.query('update club_private.matches set cancelled_at=now() where id=$1',[summer]);
const late=await fixture('2028-08-10','21:00','2028-08-10T12:00:00Z');assert.equal(await pump('2028-08-10T12:05:00Z'),0);assert.equal(await pump('2028-08-10T18:00:00Z'),9);await db.query('update club_private.matches set cancelled_at=now() where id=$1',[late]);
const outage=await fixture('2028-09-10');assert.equal(await pump('2028-09-10T18:30:00Z'),9);assert.equal((await notes(outage)).length,9);await db.query('update club_private.matches set cancelled_at=now() where id=$1',[outage]);
await as(1);await act('reminder_settings',{...reminderConfig,result_repeat_enabled:true,result_repeat_hours:24,result_max_reminders:3});await db.exec('reset role');
const repeated=await fixture('2028-10-10');assert.equal(await pump('2028-10-10T21:00:00Z'),2);assert.equal(await pump('2028-10-11T21:00:00Z'),2);assert.equal(await pump('2028-10-12T21:00:00Z'),2);assert.equal(await pump('2028-10-13T21:00:00Z'),0);assert.equal((await notes(repeated)).length,6);
await as(1);const reminderResult=Object.fromEntries([...reminderA,...reminderB].map(id=>[id,{goals:0,own:0,present:true}]));await act('result',{id:repeated,result:reminderResult});await db.exec('reset role');assert.equal(await pump('2028-10-14T21:00:00Z'),0);
assert.equal((await db.query(`select count(*) n from club_private.push_queue q join club_private.notifications n on n.id=q.notification_id where n.match_id=$1 and q.status<>'sent'`,[repeated])).rows[0].n,0);
await as(1);await act('reminder_settings',{...reminderConfig,participant_enabled:false,result_enabled:false});await db.exec('reset role');const disabled=await fixture('2028-11-10');assert.equal(await pump('2028-11-10T12:00:00Z'),0);assert.equal(await pump('2028-11-10T22:00:00Z'),0);await db.query('update club_private.matches set cancelled_at=now() where id=$1',[disabled]);
await as(1);await act('reminder_settings',reminderConfig);await db.exec('reset role');
// Rescheduling suppresses the old queue and uses the new date for future reminders.
const moved=await fixture('2028-12-10');assert.equal(await pump('2028-12-10T12:00:00Z'),9);
await as(1);await act('match_edit',{id:moved,date:'2028-12-17',time:'21:00',field:'Moved Arena',a:reminderA,b:reminderB});await db.exec('reset role');
assert.equal((await db.query(`select count(*) n from club_private.push_queue q join club_private.notifications n on n.id=q.notification_id where n.match_id=$1 and n.reminder_key is not null and q.status<>'sent'`,[moved])).rows[0].n,0);
assert.equal(await pump('2028-12-17T12:00:00Z'),9);assert.ok((await notes(moved)).some(n=>n.text.includes('2028-12-17')&&n.text.includes('Moved Arena')));
await as(1);await act('reminder_settings',{...reminderConfig,first_enabled:false});await db.exec('reset role');await pump('2028-12-17T12:05:00Z');
assert.equal((await db.query(`select count(*) n from club_private.push_queue q join club_private.notifications n on n.id=q.notification_id where n.match_id=$1 and n.reminder_key is not null and q.status<>'sent'`,[moved])).rows[0].n,0);
await as(1);await act('match_cancel',{id:moved});await act('reminder_settings',reminderConfig);await db.exec('reset role');
// Existing sender RPC automatically generates reminders without changing the Edge Function.
await db.exec("update club_private.push_queue set status='sent'");
const real=(await db.query(`insert into club_private.matches(season,match_date,match_time,field,team_a,team_b,updated_at)
select $1,((now()+interval '7 hours 58 minutes') at time zone 'Europe/Rome')::date,((now()+interval '7 hours 58 minutes') at time zone 'Europe/Rome')::time,'Live reminder test',$2,$3,now()-interval '1 day' returning id`,[reminderSeason,JSON.stringify(reminderA),JSON.stringify(reminderB)])).rows[0].id;
await as(1,'service_role');const automaticJobs=(await db.query('select public.club_claim_push(20) x')).rows[0].x;assert.equal(automaticJobs.length,9);assert.ok(automaticJobs.every(j=>j.body.includes('Live reminder test')));
await as(1);await act('match_cancel',{id:real});await as(1,'service_role');const afterCancel=(await db.query('select public.club_claim_push(20) x')).rows[0].x;assert.ok(afterCancel.every(j=>!j.body.startsWith('Promemoria partita')));
// Player editing preserves identity/history and safely converts account membership.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261006_edit_player.sql',import.meta.url),'utf8'));await as(1);
const editProfile={id:4,name:'Mario Aggiornato',role:'Portiere',occasional:false};
await as(4);await rejects(()=>act('player_edit',editProfile));await as(1);
await rejects(()=>act('player_edit',{...editProfile,name:'  '}));await rejects(()=>act('player_edit',{...editProfile,role:'Invalid'}));await rejects(()=>act('player_edit',{...editProfile,occasional:'yes'}));
await rejects(()=>act('player_edit',{id:1,name:'Admin',role:'Regista',occasional:true}));await rejects(()=>act('player_edit',{id:3,name:'Admin 3',role:'Regista',occasional:true}));
await act('permission',{id:4,key:'seeAll',value:true});
const profileBefore=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
await act('player_edit',editProfile);let profileAfter=(await db.query('select public.club_snapshot(null) x')).rows[0].x;
const editedProfile=profileAfter.players.find(p=>p.id===4),oldProfile=profileBefore.players.find(p=>p.id===4);
assert.equal(editedProfile.name,'Mario Aggiornato');assert.equal(editedProfile.role,'Portiere');assert.equal(editedProfile.email,oldProfile.email);assert.equal(editedProfile.seeAll,true);
for(const key of ['goals','own','apps','wins','draws','losses','ratings'])assert.deepEqual(editedProfile[key],oldProfile[key]);assert.deepEqual(profileAfter.matches,profileBefore.matches);assert.deepEqual(profileAfter.hallOfFame,profileBefore.hallOfFame);
await act('round_open',{season:reminderSeason,award:'pollone'});const profileRound=(await db.query('select public.club_snapshot(null) x')).rows[0].x.rounds.find(r=>r.award==='pollone');
await as(4);await act('vote',{round:profileRound.id,candidate:4});await act('push_subscribe',{subscription:{endpoint:'https://fcm.googleapis.com/send/edit-player',keys:{auth:'test',p256dh:'test'}}});await as(1);
await act('player_edit',{...editProfile,occasional:true});profileAfter=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(profileAfter.players.find(p=>p.id===4).occasional,true);assert.equal(profileAfter.players.find(p=>p.id===4).email,null);assert.equal(profileAfter.rounds.find(r=>r.id===profileRound.id).count,1);
await as(4);await rejects(()=>db.query('select public.club_snapshot(null)'));await as(1,'supabase_auth_admin');assert.equal((await hook('p4@test.invalid')).error.http_code,403);
await db.exec('reset role');assert.equal((await db.query('select count(*) n from club_private.push_subscriptions where player_id=4')).rows[0].n,0);assert.equal((await db.query("select count(*) n from club_private.push_queue where player_id=4 and status<>'sent'")).rows[0].n,0);
assert.equal((await db.query('select count(*) n from auth.users where email=$1',['p4@test.invalid'])).rows[0].n,1);
await as(1);await act('player_edit',{...editProfile,name:'Mario Membro',occasional:false});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===4).email,null);await act('invite',{id:4,email:'p4@test.invalid'});await as(4);
const restored=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(restored.user,4);assert.equal(restored.players.find(p=>p.id===4).name,'Mario Membro');assert.equal(restored.players.find(p=>p.id===4).seeAll,false);assert.equal(restored.rounds.find(r=>r.id===profileRound.id).voted,true);
// Match summary grants are enforced in the returned JSON, not only in the UI.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_match_player_summary.sql',import.meta.url),'utf8'));await as(1);
const summaryAdmin=await snapshot(2027);const summaryGame=summaryAdmin.matches.find(m=>m.result&&Object.keys(m.result).length===10);assert.ok(summaryGame);
await as(4);let summaryPrivate=await snapshot(2027);assert.deepEqual(Object.keys(summaryPrivate.matches.find(m=>m.id===summaryGame.id).result),['4']);
await as(1);await act('permission',{id:4,key:'seeAll',value:true});await as(4);assert.equal(Object.keys((await snapshot(2027)).matches.find(m=>m.id===summaryGame.id).result).length,10);
await as(1);await act('permission',{id:4,key:'seeAll',value:false});
// Detailed history is admin-only and never logs secret vote choices; restoration keeps IDs/statistics.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_history_and_player_recovery.sql',import.meta.url),'utf8'));await as(1);
await act('ratings',{id:4,ratings:[71,72,73,74,75,76]});let history=(await db.query('select public.club_admin_history() x')).rows[0].x;const ratingChange=history.changes.find(a=>a.action==='ratings');assert.equal(ratingChange.actor_name,'Player 1');assert.deepEqual(ratingChange.details.after.ratings,[71,72,73,74,75,76]);assert.ok(ratingChange.details.before.ratings);
await as(4);await rejects(()=>db.query('select public.club_admin_history()'));await rejects(()=>act('player_restore',{id:4}));await as(1);
const beforeRemoval=(await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===4);await act('player_delete',{id:4});history=(await db.query('select public.club_admin_history() x')).rows[0].x;assert.ok(history.deletedPlayers.some(p=>p.id===4));
await act('player_restore',{id:4});const recovered=(await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===4);for(const key of ['id','name','role','ratings','goals','own','apps','wins','draws','losses'])assert.deepEqual(recovered[key],beforeRemoval[key]);assert.equal(recovered.email,null);assert.equal(recovered.admin,false);assert.equal(recovered.seeAll,false);
assert.ok(!(await db.query('select public.club_admin_history() x')).rows[0].x.deletedPlayers.some(p=>p.id===4));await rejects(()=>act('player_restore',{id:4}));
await act('invite',{id:4,email:'p4@test.invalid'});await as(4);await act('vote',{round:profileRound.id,candidate:1});await as(1);history=(await db.query('select public.club_admin_history() x')).rows[0].x;assert.ok(history.changes.every(a=>a.action!=='vote'&&!('candidate' in a.details)));
await db.exec('reset role;set role anon');await rejects(()=>db.query('select public.club_admin_history()'));
// Deactivation keeps data and membership, denies access, and publishes only the presence flag.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_player_activation.sql',import.meta.url),'utf8'));await as(1);
const activeBefore=(await db.query('select public.club_snapshot(null) x')).rows[0].x;const fourBefore=activeBefore.players.find(p=>p.id===4);
await as(5);await rejects(()=>act('player_active',{id:4,active:false}));await as(1);await rejects(()=>act('player_active',{id:1,active:false}));await rejects(()=>act('player_active',{id:3,active:false}));
await act('player_active',{id:4,active:false});let inactiveState=(await db.query('select public.club_snapshot(null) x')).rows[0].x;const inactiveFour=inactiveState.players.find(p=>p.id===4);assert.equal(inactiveFour.active,false);assert.equal(inactiveFour.hasPresence,true);for(const key of ['apps','goals','ratings','email'])assert.deepEqual(inactiveFour[key],fourBefore[key]);
await as(4);await rejects(()=>db.query('select public.club_snapshot(null)'));await as(1,'supabase_auth_admin');assert.equal((await hook('p4@test.invalid')).error.http_code,403);
await as(5);inactiveState=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(inactiveState.players.find(p=>p.id===4).hasPresence,true);assert.equal(inactiveState.players.find(p=>p.id===4).apps,undefined);await as(1);
const absentInactive=await act('player',{name:'Inactive zero appearances',role:'Regista',occasional:true,email:''});await act('player_active',{id:absentInactive.id,active:false});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===absentInactive.id).hasPresence,false);
await rejects(()=>act('permission',{id:4,key:'admin',value:true}));await rejects(()=>act('match',{season:reminderSeason,date:'2030-05-01',time:'21:00',field:'Test',a:[1,3,4,5,6],b:[7,8,9,10,absentInactive.id]}));
await act('player_active',{id:4,active:true});await as(4);assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.user,4);await as(1);
const scheduledWithFour=await act('match',{season:reminderSeason,date:'2030-05-01',time:'21:00',field:'Test',a:reminderA,b:reminderB});await rejects(()=>act('player_active',{id:4,active:false}));await act('match_cancel',{id:scheduledWithFour.id});await act('player_active',{id:4,active:false});
assert.equal((await db.query('select public.club_admin_history() x')).rows[0].x.changes[0].action,'player_active');
// Device endpoints cannot reveal or remove another member's subscriptions.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_device_push.sql',import.meta.url),'utf8'));await as(1);
const deviceEndpoint='https://fcm.googleapis.com/device-test';await act('push_subscribe',{subscription:{endpoint:deviceEndpoint,keys:{auth:'test',p256dh:'test'}}});
const device=async(disable=false)=>(await db.query('select public.club_device_push($1,$2) x',[deviceEndpoint,disable])).rows[0].x;
assert.equal((await device()).active,true);await as(5);assert.equal((await device()).active,false);await device(true);await as(1);assert.equal((await device()).active,true);await device(true);assert.equal((await device()).active,false);
await as(4);await rejects(()=>device());await db.exec('reset role;set role anon');await rejects(()=>device());
// Pair statistics respect presence, cancellation, own goals, season and server permissions.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_pair_statistics.sql',import.meta.url),'utf8'));
await db.exec(`insert into club_private.seasons(id,name,started_on,closed_at) values(2099,'Pairs test','2099-01-01',now());
insert into club_private.matches(season,match_date,match_time,field,team_a,team_b,result) values
(2099,'2099-01-01','21:00','Test','[1,5]','[6,7]','{"1":{"goals":1,"own":0,"present":true},"5":{"goals":0,"own":0,"present":true},"6":{"goals":0,"own":1,"present":true},"7":{"goals":0,"own":0,"present":false}}'),
(2099,'2099-01-02','21:00','Test','[1,6]','[5,7]','{"1":{"goals":0,"own":0,"present":true},"6":{"goals":0,"own":0,"present":true},"5":{"goals":0,"own":0,"present":true},"7":{"goals":0,"own":0,"present":true}}');`);
await as(1);const pairSnapshot=async()=>(await db.query('select public.club_pair_statistics(2099) x')).rows[0].x;let pairs=await pairSnapshot();assert.equal(pairs.ownOnly,false);let allied=pairs.pairs.find(r=>r.first===1&&r.second===5&&r.together);assert.deepEqual(allied,{first:1,second:5,together:true,games:1,wins:1,draws:0,losses:0});assert.ok(!pairs.pairs.some(r=>r.first===6&&r.second===7&&r.together));
await as(5);pairs=await pairSnapshot();assert.equal(pairs.ownOnly,true);assert.ok(pairs.pairs.every(r=>r.first===5||r.second===5));assert.ok(pairs.pairs.some(r=>!r.together&&r.draws===1));
await as(1);await act('permission',{id:5,key:'seeAll',value:true});await as(5);assert.equal((await pairSnapshot()).ownOnly,false);await as(1);await act('permission',{id:5,key:'seeAll',value:false});
await db.exec("reset role;update club_private.matches set cancelled_at=now() where season=2099 and match_date='2099-01-01'");await as(1);assert.ok(!(await pairSnapshot()).pairs.some(r=>r.together&&r.first===1&&r.second===5));await rejects(()=>db.query('select public.club_pair_statistics(-1)'));await as(4);await rejects(()=>pairSnapshot());await db.exec('reset role;set role anon');await rejects(()=>pairSnapshot());
// Image mutation is admin-only, raster-only and size-bounded; recovery keeps the avatar.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_player_images.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20261007_player_images_512.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20261007_player_images_original_webp.sql',import.meta.url),'utf8'));await as(1);
const imageGuest=await act('player',{name:'Avatar Guest',role:'Regista',occasional:true,email:''});const avatarData='data:image/png;base64,iVBORw0KGgo=';
const imageAction=async(image,id=imageGuest.id)=>db.query('select public.club_player_image($1,$2)',[id,image]);await imageAction(avatarData);let imageSnapshot=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(imageSnapshot.players.find(p=>p.id===imageGuest.id).image,avatarData);
await rejects(()=>imageAction('data:image/svg+xml;base64,AAAA'));await rejects(()=>imageAction('https://outside.invalid/picture.png'));await rejects(()=>imageAction('data:image/png;base64,'+'A'.repeat(1398128)));await rejects(()=>imageAction(avatarData,-1));
await as(5);await rejects(()=>imageAction(null));imageSnapshot=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(imageSnapshot.players.find(p=>p.id===imageGuest.id).image,avatarData);await as(1);
await act('player_delete',{id:imageGuest.id});await act('player_restore',{id:imageGuest.id});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id).image,avatarData);assert.ok(!JSON.stringify((await db.query('select public.club_admin_history() x')).rows[0].x).includes(avatarData));await imageAction(null);assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id).image,null);
await as(4);await rejects(()=>imageAction(avatarData));await db.exec('reset role;set role anon');await rejects(()=>imageAction(avatarData));
// Optimized snapshots omit image contents, including for admins; separate RPC enforces membership.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261007_free_plan_optimization.sql',import.meta.url),'utf8'));await as(1);await imageAction(avatarData);
const optimized=(await db.query('select public.club_snapshot(null) x')).rows[0].x;const imagePlayer=optimized.players.find(p=>p.id===imageGuest.id);assert.equal(imagePlayer.image,undefined);assert.equal(imagePlayer.imageVersion.length,32);assert.ok(!JSON.stringify(optimized).includes(avatarData));
const imageBatch=async(ids=[imageGuest.id])=>(await db.query('select public.club_player_images($1) x',[ids])).rows[0].x;assert.equal((await imageBatch())[0].image,avatarData);assert.equal((await imageBatch())[0].version,imagePlayer.imageVersion);await rejects(()=>imageBatch(Array(11).fill(imageGuest.id)));assert.ok((await db.query('select public.club_admin_history() x')).rows[0].x.changes.length<=10);
await as(5);assert.equal((await imageBatch())[0].image,avatarData);await as(4);await rejects(()=>imageBatch());await db.exec('reset role;set role anon');await rejects(()=>imageBatch());
// Cron remains every five minutes, but HTTP invocations occur only for eligible push jobs.
await db.exec(`reset role;drop schema cron cascade;drop schema vault cascade;drop schema net cascade;create schema cron;create schema vault;create schema net;
create table cron.job(jobid bigint generated always as identity,jobname text unique,schedule text,command text);
create table cron.job_run_details(jobid bigint,end_time timestamptz);
create table vault.decrypted_secrets(name text,decrypted_secret text);
insert into vault.decrypted_secrets values('club_project_url','https://test.invalid'),('club_publishable_key','public-test'),('club_cron_secret','test-only');
create function cron.schedule(text,text,text) returns bigint language plpgsql as $$declare n bigint;begin insert into cron.job(jobname,schedule,command) values($1,$2,$3) on conflict(jobname) do update set schedule=excluded.schedule,command=excluded.command returning jobid into n;return n;end $$;
create table net.test_calls(id bigint generated always as identity);
create function net.http_post(url text,headers jsonb,body jsonb,timeout_milliseconds integer) returns bigint language plpgsql as $$declare n bigint;begin insert into net.test_calls default values returning id into n;return n;end $$;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261007_free_plan_optimization.sql',import.meta.url),'utf8'));const cronJob=(await db.query("select * from cron.job where jobname='chicken-futsal-send-push'")).rows[0];assert.equal(cronJob.schedule,'*/5 * * * *');await db.exec("update club_private.push_queue set status='sent'");await db.exec(cronJob.command);assert.equal((await db.query('select count(*)::int n from net.test_calls')).rows[0].n,0);
await db.exec(`insert into club_private.push_subscriptions(player_id,endpoint,subscription) values(1,'https://fcm.googleapis.com/cron-test','{}') on conflict do nothing;
insert into club_private.push_queue(player_id,notification_id) select 1,id from club_private.notifications where player_id=1 limit 1;`);await db.exec(cronJob.command);assert.equal((await db.query('select count(*)::int n from net.test_calls')).rows[0].n,1);
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261008_default_player_images.sql',import.meta.url),'utf8'));await as(1);
const defaultAction=async(n)=>(await db.query('select public.club_player_default_image($1,$2)',[imageGuest.id,n]));assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id).defaultImage,1);await imageAction(avatarData);await defaultAction(2);let defaultPlayer=(await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id);assert.equal(defaultPlayer.defaultImage,2);assert.equal(defaultPlayer.imageVersion,null);await rejects(()=>defaultAction(3));await rejects(()=>defaultAction(null));await as(5);await rejects(()=>defaultAction(1));await as(1);await act('player_delete',{id:imageGuest.id});await act('player_restore',{id:imageGuest.id});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id).defaultImage,2);await imageAction(avatarData);await imageAction(null);assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===imageGuest.id).defaultImage,2);
// Performance judgments: decimal values, configuration, replacement, bounds and reversals.
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261009_match_performance.sql',import.meta.url),'utf8'));await as(1);await act('player_active',{id:4,active:true});
const pr=async(id)=>(await db.query('select public.club_snapshot(null) x')).rows[0].x.players.find(p=>p.id===id).ratings;
const performanceMatch=async()=>act('match',{season:reminderSeason,date:'2031-01-01',time:'21:00',field:'Performance',a:reminderA,b:reminderB});
const performanceResult=()=>Object.fromEntries([...reminderA,...reminderB].map(id=>[id,{goals:0,own:0,present:true,performance:null}]));
await act('ratings',{id:6,ratings:[60,60,60,60,60,60]});assert.equal((await db.query('select public.club_snapshot(null) x')).rows[0].x.performanceSettings.step,0.5);
const pm1=await performanceMatch(),pm2=await performanceMatch();let rr1=performanceResult(),rr2=performanceResult();rr1[6].performance='above';rr2[6].performance='below';await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(60.5));await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(60.5));await act('result',{id:pm2.id,result:rr2});assert.deepEqual(await pr(6),Array(6).fill(60));
await act('performance_settings',{step:1});rr1[6].goals=1;await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(60));rr1[6].performance='below';await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(58.5));rr1[6].performance=null;await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(59.5));
await act('performance_settings',{step:0});rr1[6].performance='above';await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(59.5));await act('performance_settings',{step:0.5});await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(59.5));rr1[6].performance='same';await act('result',{id:pm1.id,result:rr1});rr1[6].performance='above';await act('result',{id:pm1.id,result:rr1});assert.deepEqual(await pr(6),Array(6).fill(60));await act('match_cancel',{id:pm2.id});assert.deepEqual(await pr(6),Array(6).fill(60.5));
await rejects(()=>act('performance_settings',{step:-1}));await rejects(()=>act('performance_settings',{step:5.1}));await rejects(()=>act('performance_settings',{step:0.001}));await rejects(()=>act('performance_settings',{step:null}));await as(5);await rejects(()=>act('performance_settings',{step:1}));await rejects(()=>act('result',{id:pm1.id,result:rr1}));await rejects(()=>db.query('select * from club_private.rating_events'));await rejects(()=>db.query('select club_private.replay_ratings(6)'));let ownPerformance=(await db.query('select public.club_snapshot(null) x')).rows[0].x;assert.equal(ownPerformance.players.find(p=>p.id===6).ratings,undefined);assert.equal(ownPerformance.matches.find(m=>m.id===pm1.id).result['6'],undefined);await as(1);
await act('performance_settings',{step:0.5});await act('ratings',{id:7,ratings:[99,1,98.8,1.2,60.5,70]});const pm3=await performanceMatch();const rr3=performanceResult();rr3[7].performance='above';await act('result',{id:pm3.id,result:rr3});assert.deepEqual(await pr(7),[99,1.5,99,1.7,61,70.5]);await act('result',{id:pm3.id,result:rr3});assert.deepEqual(await pr(7),[99,1.5,99,1.7,61,70.5]);rr3[7].performance='below';await act('result',{id:pm3.id,result:rr3});assert.deepEqual(await pr(7),[98.5,1,98.3,1,60,69.5]);rr3[7].present=false;await rejects(()=>act('result',{id:pm3.id,result:rr3}));assert.deepEqual(await pr(7),[98.5,1,98.3,1,60,69.5]);rr3[7].performance=null;await act('result',{id:pm3.id,result:rr3});assert.deepEqual(await pr(7),[99,1,98.8,1.2,60.5,70]);rr3[7].present=true;rr3[7].performance='invalid';await rejects(()=>act('result',{id:pm3.id,result:rr3}));rr3[7].performance='above';await act('result',{id:pm3.id,result:rr3});await act('match_cancel',{id:pm3.id});assert.deepEqual(await pr(7),[99,1,98.8,1.2,60.5,70]);
// Removing a participant undoes their effect; restored profiles retain the private event history.
const replacedA=reminderA.map(id=>id===6?imageGuest.id:id);await act('match_edit',{id:pm1.id,date:'2031-01-01',time:'21:00',field:'Performance',a:replacedA,b:reminderB});assert.deepEqual(await pr(6),Array(6).fill(60));let replacedResult=(await db.query('select public.club_snapshot(null) x')).rows[0].x.matches.find(m=>m.id===pm1.id).result;replacedResult[imageGuest.id]={goals:0,own:0,present:true,performance:'above'};await act('result',{id:pm1.id,result:replacedResult});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(60.5));await act('player_delete',{id:imageGuest.id});await act('player_restore',{id:imageGuest.id});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(60.5));replacedResult[imageGuest.id].performance='same';await act('result',{id:pm1.id,result:replacedResult});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(60));await act('ratings',{id:imageGuest.id,ratings:Array(6).fill(66.5)});replacedResult[imageGuest.id].performance='below';await act('result',{id:pm1.id,result:replacedResult});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(66.5));await act('match_cancel',{id:pm1.id});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(66.5));
const performanceHistory=(await db.query('select public.club_admin_history() x')).rows[0].x;assert.ok(performanceHistory.changes.some(c=>c.action==='performance_ratings'&&c.details.before.ratings&&c.details.after.ratings));
// Cancelling a played match after a guest was deleted must reverse their event before recovery.
const orphanMatch=await performanceMatch();const orphanA=reminderA.map(id=>id===6?imageGuest.id:id);await act('match_edit',{id:orphanMatch.id,date:'2031-01-01',time:'21:00',field:'Performance',a:orphanA,b:reminderB});const orphanResult=Object.fromEntries([...orphanA,...reminderB].map(id=>[id,{goals:0,own:0,present:true,performance:id===imageGuest.id?'above':null}]));await act('result',{id:orphanMatch.id,result:orphanResult});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(67));await act('player_delete',{id:imageGuest.id});await act('match_cancel',{id:orphanMatch.id});await act('player_restore',{id:imageGuest.id});assert.deepEqual(await pr(imageGuest.id),Array(6).fill(66.5));
// One-off restoration retains the result, restores its rating effects, and is safe to repeat.
await db.exec('reset role');
await db.query("update club_private.seasons set name='2025/2026' where id=$1",[reminderSeason]);
await db.query("update club_private.matches set match_date='2026-10-09',match_time='21:00',field='Oratorio Don Bosco Arena' where id=$1",[pm3.id]);
const restoreSQL=await readFile(new URL('../supabase/operations/20261009_reactivate_test_match.sql',import.meta.url),'utf8');
const originalResult=(await db.query('select result from club_private.matches where id=$1',[pm3.id])).rows[0].result;
await db.exec(restoreSQL);assert.deepEqual(await pr(7),[99,1.5,99,1.7,61,70.5]);
assert.deepEqual((await db.query('select result,cancelled_at from club_private.matches where id=$1',[pm3.id])).rows[0],{result:originalResult,cancelled_at:null});
await db.exec(restoreSQL);assert.deepEqual(await pr(7),[99,1.5,99,1.7,61,70.5]);
assert.equal((await db.query("select count(*)::int n from club_private.audit where action='match_restore'")).rows[0].n,1);
await db.exec(await readFile(new URL('../supabase/migrations/20261009_performance_step_choices.sql',import.meta.url),'utf8'));
await as(1);await rejects(()=>act('performance_settings',{step:0.25}));await rejects(()=>act('performance_settings',{step:2}));for(const step of [0,0.5,1])await act('performance_settings',{step});
await db.exec('reset role');await db.exec(await readFile(new URL('../supabase/migrations/20261009_purge_deleted_player.sql',import.meta.url),'utf8'));
await as(1);await act('player_delete',{id:imageGuest.id});
const purge=async confirmation=>db.query('select public.club_player_purge($1,$2)',[imageGuest.id,confirmation]);
await rejects(()=>purge(''));await as(5);await rejects(()=>purge('ELIMINA DEFINITIVAMENTE'));await as(1);
const historicalMatches=(await db.query('select public.club_snapshot(null) x')).rows[0].x.matches;
await purge('ELIMINA DEFINITIVAMENTE');await rejects(()=>act('player_restore',{id:imageGuest.id}));await rejects(()=>purge('ELIMINA DEFINITIVAMENTE'));
assert.deepEqual((await db.query('select public.club_snapshot(null) x')).rows[0].x.matches,historicalMatches);
await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from club_private.deleted_players where player_id=$1',[imageGuest.id])).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from club_private.rating_events where player_id=$1',[imageGuest.id])).rows[0].n,0);
await as(1);await rejects(()=>db.query("select public.club_player_purge(1,'ELIMINA DEFINITIVAMENTE')"));
await db.close();console.log('PASS database: private tables, membership, permissions, own statistics, duplicate votes, self votes, 4 rounds, independent awards, seasons, result corrections, notifications, service-only push queue');
